### ISSUE TITLE
`getAvailableCameraDevices()` throws "Extension mode does not exist" on Infinix devices 🐛 

### ISSUE THREAD

**Issue by pdsouza** [cuvent/react-native-vision-camera#1088]
### What were you trying to do?

I wanted to see the camera preview on my Infinix device.

### Reproduceable Code

```tsx
const availableCameras = await Camera.getAvailableCameraDevices();
```

### What happened instead?

When I call `getAvailableCameraDevices` on my Infinix device, it throws error `unknown/unknown: [unknown/unknown] Extension mode does not exist: 2` and the camera preview shows a black screen.

I found that an `IllegalArugmentException` is thrown when calling `ExtensionsManager.isExtensionAvailable()` in `CameraViewModule.kt`. I am currently working around this by catching the exception and falling back to values of `false` for `supportsHdr` and `supportsLowLightBoost`. This is my current working patch to `CameraViewModule.kt`:

```
diff --git a/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt b/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt
index 92dcc93..dd8a3a7 100644
--- a/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt
+++ b/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt
@@ -180,8 +180,18 @@ class CameraViewModule(reactContext: ReactApplicationContext) : ReactContextBase
           else null
           val fpsRanges = characteristics.get(CameraCharacteristics.CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES)!!

-          val supportsHdr = extensionsManager.isExtensionAvailable(cameraSelector, ExtensionMode.HDR)
-          val supportsLowLightBoost = extensionsManager.isExtensionAvailable(cameraSelector, ExtensionMode.NIGHT)
+          val supportsHdr = try {
+            extensionsManager.isExtensionAvailable(cameraSelector, ExtensionMode.HDR)
+          } catch (e: IllegalArgumentException) {
+            Log.w(TAG, "Caught exception while checking for supportsHdr, falling back to false: $e")
+            false
+          };
+          val supportsLowLightBoost = try {
+            extensionsManager.isExtensionAvailable(cameraSelector, ExtensionMode.NIGHT)
+          } catch (e: IllegalArgumentException) {
+            Log.w(TAG, "Caught exception while checking for supportsLowLightBoost, falling back to false: $e")
+            false
+          };
           // see https://developer.android.com/reference/android/hardware/camera2/CameraDevice#regular-capture
           val supportsParallelVideoProcessing = hardwareLevel != CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY && hardwareLevel != CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
 ```
 
Happy to send a PR with the above patch with any suggested adjustments.

### Relevant log output

```shell
2022-06-09 20:07:52.335 5484-5594/com.locket.Locket W/System.err: java.lang.IllegalArgumentException: Extension mode does not exist: 2
2022-06-09 20:07:52.335 5484-5594/com.locket.Locket W/System.err:     at androidx.camera.extensions.internal.BasicVendorExtender.<init>(BasicVendorExtender.java:95)
2022-06-09 20:07:52.335 5484-5594/com.locket.Locket W/System.err:     at androidx.camera.extensions.ExtensionsInfo.getVendorExtender(ExtensionsInfo.java:252)
2022-06-09 20:07:52.335 5484-5594/com.locket.Locket W/System.err:     at androidx.camera.extensions.ExtensionsInfo.getFilter(ExtensionsInfo.java:197)
2022-06-09 20:07:52.335 5484-5594/com.locket.Locket W/System.err:     at androidx.camera.extensions.ExtensionsInfo.isExtensionAvailable(ExtensionsInfo.java:134)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at androidx.camera.extensions.ExtensionsManager.isExtensionAvailable(ExtensionsManager.java:413)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at com.mrousavy.camera.CameraViewModule$getAvailableCameraDevices$1.invokeSuspend(CameraViewModule.kt:186)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-06-09 20:07:52.336 5484-5594/com.locket.Locket W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineSche
```

### Device

Infinix HOT 10S

### VisionCamera Version

2.12.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! That's weird, I don't think that should throw? I'd be more than happy to have such a change merged to upstream, but if you want to create a PR for this let's use a common extension methond (something like `tryIsExtensionAvailable` that does the try catch internally so we don't repeat ourselves here inline)

**Comment by pdsouza** [comment]
Did some more research and confirmed that this issue is fixed with the latest version of this lib. I suspect it was in [v2.12.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.12.2) when the CameraX libs were updated in this commit: https://github.com/mrousavy/react-native-vision-camera/commit/a7d620cf2261147de5aa9cf1de1d45c3a226077d. `ExtensionsManager.isExtensionAvailable()` no longer throws an exception on my Infinix device. Thanks!
