### ISSUE TITLE
Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'. > java.lang.NullPointerException (no error message)🐛 

### ISSUE THREAD

**Issue by Jaybee4real** [cuvent/react-native-vision-camera#1284]
### What were you trying to do?

I was trying to build the app with the package on android

### Reproduceable Code

```tsx
Just try to run the package on android
```

### What happened instead?

The app crashes with the message above at 97% with the below error

### Relevant log output

```shell
> Task :react-native-vision-camera:generateJsonModelDebug FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
831 actionable tasks: 831 executed
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/reactnative/crashes/AppCenterReactNativeCrashesListener.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@invertase/react-native-apple-authentication/android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-firebase/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-firebase/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-firebase/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-google-signin/google-signin/android/src/main/java/com/reactnativegooglesignin/RNGoogleSigninModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-google-signin/google-signin/android/src/main/java/com/reactnativegooglesignin/RNGoogleSigninModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 41s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/reactnative/crashes/AppCenterReactNativeCrashesListener.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@invertase/react-native-apple-authentication/android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-firebase/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-firebase/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-firebase/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-google-signin/google-signin/android/src/main/java/com/reactnativegooglesignin/RNGoogleSigninModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-google-signin/google-signin/android/src/main/java/com/reactnativegooglesignin/RNGoogleSigninModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 41s

    at makeError (/Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/execa/index.js:174:9)
    at /Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/jaybee4real/Documents/Programming-codes/Daba/mobile-client/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Device

Samsung S10 plus (Android 12)

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Jaybee4real** [comment]
Hey everyone, i think i found a solution to it, please try this and don't forget to come back to indicate if it works for you! 😊

- --> **Step 1**: Go into your gradle-wrapper.properties file and upgrade your gradle version to at least version 7.0.2 
(See example image below)

<img width="603" alt="Screenshot 2022-10-17 at 15 01 37" src="https://user-images.githubusercontent.com/51276685/196197497-bf9ffc7d-0ad5-45fb-9d6a-f78db18e2eae.png">

- ---> **Step 2**: Go into your android/build.gradle and add an extra classpath to your dependencies in android/build.gradle
  `classpath 'com.android.tools.build:gradle:7.0.0'`
 (See example image below)

<img width="383" alt="Screenshot 2022-10-17 at 15 18 05" src="https://user-images.githubusercontent.com/51276685/196201324-9bbca07b-aeeb-41fb-8d12-13114e00ca7c.png">


- ---> **Optional Step**: you might want to change all your dependencies URL to use "https" instead of "http" in your allProjects.repositories in android/build.gradle as you might face an error when building if you do not do this
(See example image below)

<img width="519" alt="Screenshot 2022-10-17 at 15 04 29" src="https://user-images.githubusercontent.com/51276685/196198136-85166391-e601-4219-84ac-3e2cbc670c63.png">

**Comment by princefishthrower** [comment]
@Jaybee4real - I have two higher versions: gradle 7.2 and build:gradle:7.0.1 and I still can't build for android when this library is used in my app.

Perhaps the combination of _only_ 7.0.2 and 7.0.0 work?

**Comment by Jaybee4real** [comment]
Yes, that is what I found out @princefishthrower, you can try that

**Comment by princefishthrower** [comment]
@Jaybee4real - I still can't build after implementing these changes. What version of `react-native-vision-camera` are you using?

**Comment by Jaybee4real** [comment]
"react-native-vision-camera": "^2.14.1"

**Comment by wasiquehaider** [comment]
I fixed it by following the below steps :) 

```
- watchman watch-del-all 
- yarn cache clean --force
-  npm cache clean --force # optional - in case you have used npm
-  rm -rf node_modules/ rm yarn.lock
-  rm package-lock.json # optional - in case you have used npm 
- rm -rf $TMPDIR/metro-* 
- rm -rf $TMPDIR/haste-*
-  yarn install / npm install
-  yarn start --reset-cache
- cd ios && rm -rf Podfile.lock && rm -rf pods && pod install --verbose
```

**Comment by MohamedAhmed122** [comment]
> Hey everyone, i think i found a solution to it, please try this and don't forget to come back to indicate if it works for you! 😊
> 
> * --> **Step 1**: Go into your gradle-wrapper.properties file and upgrade your gradle version to at least version 7.0.2
>   (See example image below)
> 
> <img alt="Screenshot 2022-10-17 at 15 01 37" width="603" src="https://user-images.githubusercontent.com/51276685/196197497-bf9ffc7d-0ad5-45fb-9d6a-f78db18e2eae.png">
> 
> * ---> **Step 2**: Go into your android/build.gradle and add an extra classpath to your dependencies in android/build.gradle
>   `classpath 'com.android.tools.build:gradle:7.0.0'`
>   (See example image below)
> 
> <img alt="Screenshot 2022-10-17 at 15 18 05" width="383" src="https://user-images.githubusercontent.com/51276685/196201324-9bbca07b-aeeb-41fb-8d12-13114e00ca7c.png">
> 
> * ---> **Optional Step**: you might want to change all your dependencies URL to use "https" instead of "http" in your allProjects.repositories in android/build.gradle as you might face an error when building if you do not do this
>   (See example image below)
> 
> <img alt="Screenshot 2022-10-17 at 15 04 29" width="519" src="https://user-images.githubusercontent.com/51276685/196198136-85166391-e601-4219-84ac-3e2cbc670c63.png">

@Jaybee4real  I  followed these steps, but I end up having this error, do you know how to fix it?

```
> Task :react-native-gradle-plugin:compileKotlin FAILED

FAILURE: Build failed with an exception.
```

**Comment by Jaybee4real** [comment]
@MohamedAhmed122 

Check your bash_profile, do you see these values there?

(code ~/.bash_profile)

`export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
**export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)**`

(Especially the JAVA_HOME)

<img width="322" alt="Screenshot 2022-10-18 at 15 35 16" src="https://user-images.githubusercontent.com/51276685/196460983-87831603-ee25-45dd-834c-90dba76c08d0.png">

(EDIT): If you use a mac, you might want to check your ~/.zshrc file

**Comment by Jaybee4real** [comment]
Will be closing this now

**Comment by akhilkrishnan1268** [comment]
> Hey everyone, i think i found a solution to it, please try this and don't forget to come back to indicate if it works for you! 😊
> 
> * --> **Step 1**: Go into your gradle-wrapper.properties file and upgrade your gradle version to at least version 7.0.2
>   (See example image below)
> 
> <img alt="Screenshot 2022-10-17 at 15 01 37" width="603" src="https://user-images.githubusercontent.com/51276685/196197497-bf9ffc7d-0ad5-45fb-9d6a-f78db18e2eae.png">
> 
> * ---> **Step 2**: Go into your android/build.gradle and add an extra classpath to your dependencies in android/build.gradle
>   `classpath 'com.android.tools.build:gradle:7.0.0'`
>   (See example image below)
> 
> <img alt="Screenshot 2022-10-17 at 15 18 05" width="383" src="https://user-images.githubusercontent.com/51276685/196201324-9bbca07b-aeeb-41fb-8d12-13114e00ca7c.png">
> 
> * ---> **Optional Step**: you might want to change all your dependencies URL to use "https" instead of "http" in your allProjects.repositories in android/build.gradle as you might face an error when building if you do not do this
>   (See example image below)
> 
> <img alt="Screenshot 2022-10-17 at 15 04 29" width="519" src="https://user-images.githubusercontent.com/51276685/196198136-85166391-e601-4219-84ac-3e2cbc670c63.png">

This worked for me.

**Comment by git-kishor** [comment]
Anyone in 2025?

```
"dependencies": {
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native/new-app-screen": "0.82.0",
    "@react-navigation/native": "^7.1.18",
    "@react-navigation/native-stack": "^7.3.27",
    "hermes-engine": "^0.11.0",
    "react": "19.1.1",
    "react-native": "0.82.0",
    "react-native-barcode-scanner": "^0.1.0",
    "react-native-gesture-handler": "^2.28.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-permissions": "^5.4.2",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-native-reanimated": "^4.1.3",
    "react-native-safe-area-context": "^5.6.1",
    "react-native-screens": "^4.16.0",
    "react-native-simple-bottom-sheet": "^1.0.4",
    "react-native-svg": "^15.14.0",
    "react-native-svg-transformer": "^1.5.1",
    "react-native-vector-icons": "^10.3.0",
    "react-native-vision-camera": "^4.7.2",
    "react-native-worklets": "^0.6.1",
    "react-native-worklets-core": "^1.6.2"
  },
```

I have these. When I am using react-native-vision-camera alone (without react-native-reanimated package), that time, it works. But I want zoom functionality with the camera to scan QR code and it needs react-native-reanimated package.
Once I install react-native-reanimated, BUILD FAILED?
