### ISSUE TITLE
🐛 Error when trying to open in debug mode with android 

### ISSUE THREAD

**Issue by Skipperlla** [cuvent/react-native-vision-camera#1329]
### What were you trying to do?

While I try to open my application in android normally, when I open my application, it runs in the background, but I cannot enter the application itself in any way, when I open it in debug mode from android studio to see the error, I am faced with this error.
<img width="306" alt="Ekran Resmi 2022-11-08 19 27 25" src="https://user-images.githubusercontent.com/68515357/200620866-5f6c613b-f4a0-4103-802e-af8da671a2b8.png">

### Reproduceable Code

```tsx
2022-11-08 18:40:49.156 12341-12447/com.platereader E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.platereader, PID: 12341
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/common/internal/Detector;
        at com.visioncameraimagelabeler.VisionCameraImageLabelerPackage.createNativeModules(VisionCameraImageLabelerPackage.java:19)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1338)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:136)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1108)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.common.internal.Detector" on path: DexPathList[[zip file "/data/app/~~4T3Ju0yZs1T4llnvqHs5vg==/com.platereader-mDB2JG4lZoWuAQ_gQz0v1A==/base.apk"],nativeLibraryDirectories=[/data/app/~~4T3Ju0yZs1T4llnvqHs5vg==/com.platereader-mDB2JG4lZoWuAQ_gQz0v1A==/lib/arm64, /data/app/~~4T3Ju0yZs1T4llnvqHs5vg==/com.platereader-mDB2JG4lZoWuAQ_gQz0v1A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.visioncameraimagelabeler.VisionCameraImageLabelerPackage.createNativeModules(VisionCameraImageLabelerPackage.java:19) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1338) 
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:136) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1108) 
        at java.lang.Thread.run(Thread.java:923) 
```

### What happened instead?

i am facing this error when my app should be running

### Device

Pixel 4 API 30 (Android)

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Skipperlla** [comment]
#1014 for It's not work me
