### ISSUE TITLE
java.util.concurrent.RejectedExecutionException: Task androidx.camera.core.impl.utils.executor.SequentialExecutor 

### ISSUE THREAD

**Issue by vietmobilefolk** [cuvent/react-native-vision-camera#1351]
### What were you trying to do?

Crashlytics reported this crash

### What happened instead?

The app crash and reported to Crashlytics

### Relevant log output

```shell
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: java.util.concurrent.RejectedExecutionException: Task androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker@fd193c0 rejected from java.util.concurrent.ThreadPoolExecutor@2ad1aad[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3855]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
	at androidx.camera.core.impl.utils.executor.SequentialExecutor.execute(SequentialExecutor.java:119)
	at androidx.camera.video.internal.encoder.EncoderImpl$MediaCodecCallback.onInputBufferAvailable(EncoderImpl.java:855)
	at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1767)
	at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1705)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:247)
	at android.app.ActivityThread.main(ActivityThread.java:8676)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

       at .<unknown>(java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecutionThreadPoolExecutor.java:2086:0)
       at .<unknown>(java.util.concurrent.ThreadPoolExecutor.rejectThreadPoolExecutor.java:848:0)
       at .<unknown>(java.util.concurrent.ThreadPoolExecutor.executeThreadPoolExecutor.java:1394:0)
       at .<unknown>(java.util.concurrent.Executors$DelegatedExecutorService.executeExecutors.java:630:0)
       at .<unknown>(androidx.camera.core.impl.utils.executor.SequentialExecutor.executeSequentialExecutor.java:119:0)
       at .<unknown>(androidx.camera.video.internal.encoder.EncoderImpl$MediaCodecCallback.onInputBufferAvailableEncoderImpl.java:855:0)
       at .<unknown>(android.media.MediaCodec$EventHandler.handleCallbackMediaCodec.java:1767:0)
       at .<unknown>(android.media.MediaCodec$EventHandler.handleMessageMediaCodec.java:1705:0)
       at .<unknown>(android.os.Handler.dispatchMessageHandler.java:106:0)
       at .<unknown>(android.os.Looper.loopLooper.java:247:0)
       at .<unknown>(android.app.ActivityThread.mainActivityThread.java:8676:0)
       at .<unknown>(com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runRuntimeInit.java:602:0)
       at .<unknown>(com.android.internal.os.ZygoteInit.mainZygoteInit.java:1130:0)
       at .anonymous(address at index.android.bundle:1:1424710)
       at .apply((native):0:0)
       at .__invokeCallback(address at index.android.bundle:1:88269)
       at .anonymous(address at index.android.bundle:1:86649)
       at .__guard(address at index.android.bundle:1:87519)
       at .invokeCallbackAndReturnFlushedQueue(address at index.android.bundle:1:86611)
```

### Device

Samsung Tab S7 

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
