### ISSUE TITLE
ENOENT (Noch such file or directory) when taking an image 🐛 

### ISSUE THREAD

**Issue by henrikzabel** [cuvent/react-native-vision-camera#1358]
### What were you trying to do?

I wanted to take a picture and afterwards display it to the user.

### Reproduceable Code

```tsx
photo = await camera.current.takePhoto({
  quality: 85,
  skipMetadata: false,
});
```

### What happened instead?

Instead of being displayed it does not show anything and returns following warning:

### Relevant log output

```shell
Possible Unhandled Promise Rejection (id: 0):
Error: ENOENT: /0/com.aicamera/cache/mrousavy7646743925382551685.jpg: open failed: ENOENT (No such file or directory), open 'ser/0/com.aicamera/cache/mrousavy7646743925382551685.jpg'
Error: ENOENT: /0/com.aicamera/cache/mrousavy7646743925382551685.jpg: open failed: ENOENT (No such file or directory), open 'ser/0/com.aicamera/cache/mrousavy7646743925382551685.jpg'
    at promiseMethodWrapper (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:2101:45)
    at readFileGeneric (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:157476:19)
    at readFile (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:157616:29)
    at setImageData (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:156789:38)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:156997:25)
    at ?anon_0_ (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:190946:13)
    at next (native)
    at asyncGeneratorStep (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:21971:26)
    at _next (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:21990:29)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/x86/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/x86/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:27701:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:27616:17)
    at _callReactNativeMicrotasksPass (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:27649:17)
    at callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:27813:44)
    at __callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:2484:46)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:2284:45)
    at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:2464:15)
    at flushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:2283:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aicamera&modulesOnly=false&runModule=true:2277:33)
```

### Device

Google Pixel 4 XL (emulated)

### VisionCamera Version

^2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by EKOzkan** [comment]
The image path you get from Vision Camera is like:
`/data/user/0/com.yourapp/cache/mrousavy123123123123.jpg`
to use/display that image, you should add 'file://' to the start of your path, so it should be like:
`file:///data/user/0/com.yourapp/cache/mrousavy123123123123.jpg`
