### ISSUE TITLE
🐛 onInitialized is called twice in Android

### ISSUE THREAD

**Issue by SMhdAsadi** [cuvent/react-native-vision-camera#1380]
### What were you trying to do?

I want to start recording as soon as Camera is initialized. So I call startRecording in onInitialized callback. It should start recording right after camera is initialized. It's OK in iOS.

### What happened instead?

onInitialized is called twice. So startRecording is called twice and different errors happen. If I ignore the first call and only call startRecording on second call it records correctly.

### Relevant log output

```shell
capture/inactive-source {"cause": {"message": "The video frame producer became inactive before any data was received.", "stacktrace": "java.lang.RuntimeException: The video frame producer became inactive before any data was received.
	at androidx.camera.video.Recorder.<clinit>(Recorder.java:269)
	at androidx.camera.video.Recorder$Builder.build(Recorder.java:2821)
	at com.mrousavy.camera.CameraView.configureSession(CameraView.kt:466)
	at com.mrousavy.camera.CameraView.access$configureSession(CameraView.kt:68)
	at com.mrousavy.camera.CameraView$update$1$1.invokeSuspend(CameraView.kt:327)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
"}, "message": "[capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.", "stacktrace": "com.mrousavy.camera.InactiveSourceError: [capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.
	at com.mrousavy.camera.CameraView_RecordVideoKt$startRecording$1.accept(CameraView+RecordVideo.kt:64)
	at com.mrousavy.camera.CameraView_RecordVideoKt$startRecording$1.accept(CameraView+RecordVideo.kt:52)
	at androidx.camera.video.Recorder$RecordingRecord.lambda$updateVideoRecordEvent$6$androidx-camera-video-Recorder$RecordingRecord(Recorder.java:2624)
	at androidx.camera.video.Recorder$RecordingRecord$$ExternalSyntheticLambda6.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: java.lang.RuntimeException: The video frame producer became inactive before any data was received.
	at androidx.camera.video.Recorder.<clinit>(Recorder.java:269)
	at androidx.camera.video.Recorder$Builder.build(Recorder.java:2821)
	at com.mrousavy.camera.CameraView.configureSession(CameraView.kt:466)
	at com.mrousavy.camera.CameraView.access$configureSession(CameraView.kt:68)
	at com.mrousavy.camera.CameraView$update$1$1.invokeSuspend(CameraView.kt:327)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 7 more
"}
```
```


### Device

ARYA I PLUS

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by SMhdAsadi** [comment]
This issue was on my side, and has nothing to do with vision camera. I was using gesture handler to start recording when user holds on a button. But this gesture was detected twice, therefore recording twice.
