### ISSUE TITLE
Im facing this error  [unknown/unknown: [unknown/unknown] Capture request failed with reason ERROR]❓ 

### ISSUE THREAD

**Issue by pooven801** [cuvent/react-native-vision-camera#1387]
### Question

This is my code => 
```
const takePhoto = async () => {
  try {
      const photo = await cameraRef.current.takePhoto({
        flash: 'off',
      })
      console.log("Photo Path : " photo.path)
    } catch (e) {
      console.log("Error : ", e)
    }

```
and return error _[unknown/unknown: [unknown/unknown] Capture request failed with reason ERROR]_

Here is the Logcat info. Please assist me with this.

```
2022-12-16 15:25:47.006 12515-12622/com.leafminikiosk D/CameraView: Finding view 253...
2022-12-16 15:25:47.008 12515-12622/com.leafminikiosk E/unknown:SoftAssertions: Unhandled SoftException
    com.facebook.react.bridge.AssertionException: Expected to run on UI thread!
        at com.facebook.react.bridge.SoftAssertions.assertCondition(SoftAssertions.java:37)
        at com.facebook.react.bridge.UiThreadUtil.assertOnUiThread(UiThreadUtil.java:32)
        at com.facebook.react.uimanager.UIManagerModule.resolveView(UIManagerModule.java:948)
        at com.mrousavy.camera.CameraViewModule.findCameraView(CameraViewModule.kt:87)
        at com.mrousavy.camera.CameraViewModule.access$findCameraView(CameraViewModule.kt:34)
        at com.mrousavy.camera.CameraViewModule$takePhoto$1.invokeSuspend(CameraViewModule.kt:96)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-12-16 15:25:47.008 12515-12622/com.leafminikiosk D/CameraView: Found view 253!
2022-12-16 15:25:47.008 12515-12622/com.leafminikiosk I/CameraView: takePhoto() called
2022-12-16 15:25:47.011 12515-12625/com.leafminikiosk D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.ImageCapture-3f3e30bc-518d-47be-9d26-578a1e25bed318611630, androidx.camera.core.Preview-48886461-6c6d-4203-a23a-328d5acfad9985947945] for camera: 0
2022-12-16 15:25:47.011 12515-12623/com.leafminikiosk D/CameraView: Taking picture...
2022-12-16 15:25:47.012 12515-12515/com.leafminikiosk D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=false, result=90
2022-12-16 15:25:47.013 12515-12515/com.leafminikiosk D/ImageCapture: Send image capture request [current, pending] = [0, 1]
2022-12-16 15:25:47.013 12515-12515/com.leafminikiosk D/ImageCapture: issueTakePicture
2022-12-16 15:25:47.013 12515-12623/com.leafminikiosk D/CameraView: Creating temp file...
2022-12-16 15:25:47.014 12515-12625/com.leafminikiosk D/CaptureSession: Attempting to submit CaptureRequest after setting
2022-12-16 15:25:47.015 12515-12625/com.leafminikiosk D/CaptureSession: Issuing request for session.
2022-12-16 15:25:47.020 12515-12625/com.leafminikiosk I/RequestQueue: Repeating capture request cancelled.
2022-12-16 15:25:47.020 12515-12625/com.leafminikiosk I/RequestQueue: Repeating capture request set.
2022-12-16 15:25:47.024 12515-13996/com.leafminikiosk W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
2022-12-16 15:25:47.025 12515-13996/com.leafminikiosk W/LegacyRequestMapper: convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
2022-12-16 15:25:47.059 12515-12626/com.leafminikiosk D/Camera2CameraImpl: {Camera@b857b0d[id=0]} Issue capture request
2022-12-16 15:25:47.060 12515-12626/com.leafminikiosk D/CaptureSession: Issuing capture request.
2022-12-16 15:25:47.088 12515-13996/com.leafminikiosk W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
2022-12-16 15:25:47.090 12515-13996/com.leafminikiosk W/LegacyRequestMapper: convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
2022-12-16 15:25:47.984 12515-13973/com.leafminikiosk I/RequestThread-0: Received jpeg.
2022-12-16 15:25:47.984 12515-13973/com.leafminikiosk I/RequestThread-0: Producing jpeg buffer...
2022-12-16 15:25:47.999 12515-12515/com.leafminikiosk W/ImageReader_JNI: Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
2022-12-16 15:25:48.000 12515-12515/com.leafminikiosk D/MetadataImageReader: Failed to acquire next image.
    java.lang.IllegalStateException: maxImages (2) has already been acquired, call #close before acquiring more.
        at android.media.ImageReader.acquireNextImage(ImageReader.java:502)
        at androidx.camera.core.AndroidImageReaderProxy.acquireNextImage(AndroidImageReaderProxy.java:81)
        at androidx.camera.core.MetadataImageReader.imageIncoming(MetadataImageReader.java:322)
        at androidx.camera.core.MetadataImageReader.lambda$new$0$androidx-camera-core-MetadataImageReader(MetadataImageReader.java:65)
        at androidx.camera.core.MetadataImageReader$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
        at androidx.camera.core.AndroidImageReaderProxy.lambda$setOnImageAvailableListener$0$androidx-camera-core-AndroidImageReaderProxy(AndroidImageReaderProxy.java:141)
        at androidx.camera.core.AndroidImageReaderProxy$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### VisionCamera Version

2.15.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by camboYY** [comment]
same issue happen in v3.4.7
