### ISSUE TITLE
🐛 Android app crashes with java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by Maksim-Malikov** [cuvent/react-native-vision-camera#1402]
### What were you trying to do?

We have 51 crash events in firebase console. 

### What happened instead?

The app crashes with error: 
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.mrousavy.camera.frameprocessor.FrameProcessorRuntimeManager.<init>(FrameProcessorRuntimeManager.kt:81)
       at com.mrousavy.camera.CameraViewModule.initialize$lambda-0(CameraViewModule.kt:66)
       at com.mrousavy.camera.CameraViewModule.$r8$lambda$YiRnUrObfbO8oH48lnR0UOsrros()
       at com.mrousavy.camera.CameraViewModule$$ExternalSyntheticLambda2.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:933)

### Relevant log output

```shell
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.mrousavy.camera.frameprocessor.FrameProcessorRuntimeManager.<init>(FrameProcessorRuntimeManager.kt:81)
       at com.mrousavy.camera.CameraViewModule.initialize$lambda-0(CameraViewModule.kt:66)
       at com.mrousavy.camera.CameraViewModule.$r8$lambda$YiRnUrObfbO8oH48lnR0UOsrros()
       at com.mrousavy.camera.CameraViewModule$$ExternalSyntheticLambda2.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:933)
```

### Device

Android only. Samsung Galaxy A12, Galaxy M31, Galaxy A7 (2018) etc.,  HONOR X8,  OPPO CPH2219, A57 

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
