### ISSUE TITLE
🐛 An unknown camera error occured.

### ISSUE THREAD

**Issue by liancp** [cuvent/react-native-vision-camera#1437]
### What were you trying to do?

An unknown camera error occured.

### Reproduceable Code

```tsx
An unknown camera error occured.
```

### What happened instead?

An unknown camera error occured.

### Relevant log output

```shell
2023-01-28 14:21:42.888  1292-2082  System.err                                           W  java.lang.NullPointerException
2023-01-28 14:21:42.889  1292-2082  System.err                                           W  	at com.mrousavy.camera.utils.CameraCharacteristicsUtilsKt.getDeviceTypes(CameraCharacteristicsUtils.kt:30)
2023-01-28 14:21:42.889  1292-2082  System.err                                            W  	at com.mrousavy.camera.CameraViewModule$getAvailableCameraDevices$1.invokeSuspend(CameraViewModule.kt:184)
2023-01-28 14:21:42.889  1292-2082  System.err                                            W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-01-28 14:21:42.889  1292-2082  System.err                                            W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-01-28 14:21:42.889  1292-2082  System.err                                           W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2023-01-28 14:21:42.889  1292-2082  System.err                                           W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-01-28 14:21:42.889  1292-2082  System.err                                           W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2023-01-28 14:21:42.889  1292-2082  System.err                                           W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2023-01-28 14:21:43.094  1292-4059  unknown:Re...gWebSocket com.mrs                              W  Couldn't connect to "ws://localhost:8081/message?device=rk3399-Android10%20-%2010%20-%20API%2029&app=com.mrs&clientid=DevSupportManagerImpl", will silently retry
2023-01-28 14:21:43.408  1292-1656  ReactNativeJS                                        I  FaceIdentification Component | Camera permission status: authorized

2023-01-28 14:21:44.902  1292-1656  ReactNativeJS                                     W  Possible Unhandled Promise Rejection (id: 24):
                                                                                                    unknown/unknown: [unknown/unknown] An unknown camera error occured.
                                                                                                    [unknown/unknown]: [unknown/unknown] An unknown camera error occured.
                                                                                                      


### Device

Android 10

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
I'll try something: https://github.com/mrousavy/react-native-vision-camera/pull/1467

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
