### ISSUE TITLE
when I press startRecording button an error occurs after adding 'frameProcessor' props.🐛 

### ISSUE THREAD

**Issue by JEONGEUN0204** [cuvent/react-native-vision-camera#1605]
### What were you trying to do?

I want to face detection while recording. so I added frameProcessor.

### Reproduceable Code

```tsx
//recording button
const handleRecordingButton = async () => {
    if (isRecording) {
      setDuration(null);
      await camera.current?.stopRecording();
    } else {
      setStartTime(new Date().getTime());
      await camera.current?.startRecording({
        flash: 'on',
        onRecordingFinished: video =>
          CameraRoll.save(video.path, {type: 'video', album: 'Marble'}),
        onRecordingError: error => console.error('startRecording:', error),
      });
    }
    setIsRecording(!isRecording);
  };

//frameProcessor
const frameProcessor = useFrameProcessor(
    frame => {
      'worklet';
      console.log('frame', frame);
    },
    [sensitivity],
  );

//return part
<Camera
        ref={camera}
        style={StyleSheet.absoluteFill}
        device={device}
        isActive={true}
        video={true}
        audio={true}
        format={format}
        frameProcessor={
          device.supportsParallelVideoProcessing ? frameProcessor : undefined
        }
        frameProcessorFps={1}
        orientation="portrait"
        onFrameProcessorPerformanceSuggestionAvailable={
          onFrameProcessorSuggestionAvailable
        }
      />
```

### What happened instead?

A black screen appears before the button is pressed, and an error occurs after the button is pressed.
when I delete frameProcessor prop, everything is okay.

### Relevant log output

```shell
<emulator>
//console
startRecording: {"cause": {"message": null, "stacktrace": "java.lang.NullPointerException
        at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:37)
        at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:119)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying 
to start a video recording!", "userInfo": null}

//Android Studio Logcat
--------- beginning of main
2023-05-29 01:35:56.106 28542-4309  TrafficStats            com.client                           D  tagSocket(111) with statsTag=0xffffffff, statsUid=-1
2023-05-29 01:35:56.107   388-4310  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:35:57.110   482-482   adbd                    adbd                                 W  timeout expired while flushing socket, closing
2023-05-29 01:35:58.113 28542-4313  TrafficStats            com.client                           D  tagSocket(111) with statsTag=0xffffffff, statsUid=-1
2023-05-29 01:35:58.114   388-4314  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:36:00.026   912-1094  EGL_emulation           com.android.systemui                 D  app_time_stats: avg=3870.16ms min=15.79ms max=19260.17ms count=5
--------- beginning of kernel
2023-05-29 01:36:00.120   388-4317  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:36:01.484     0-0     logd                    kernel                               I  logdr: UID=2000 GID=2000 PID=4320 b tail=0 logMask=99 pid=0 start=0ns deadline=0ns
2023-05-29 01:36:02.126   388-4323  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:36:02.599   912-1094  EGL_emulation           com.android.systemui                 D  app_time_stats: avg=2573.01ms min=2573.01ms max=2573.01ms count=1
2023-05-29 01:36:02.746  1282-1282  TaplEvents              com...le.android.apps.nexuslauncher  D  TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=768.9551, y[0]=2710.8643, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=22727700, downTime=22727700, deviceId=12, source=0x5002, displayId=0, eventId=138933174 }
2023-05-29 01:36:02.786 28542-28606 EGL_emulation           com.client                           D  app_time_stats: avg=147510.55ms min=1.75ms max=1327568.00ms count=9
2023-05-29 01:36:02.824  1282-1282  TaplEvents              com...le.android.apps.nexuslauncher  D  TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=768.9551, y[0]=2710.8643, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=22727780, downTime=22727700, deviceId=12, source=0x5002, displayId=0, eventId=72697099 }
2023-05-29 01:36:02.839 28542-28682 CameraView              com.client                           D  Finding view 35...
2023-05-29 01:36:02.840 28542-28682 unknown:SoftAssertions  com.client                           E  Unhandled SoftException
                                                                                                    com.facebook.react.bridge.AssertionException: Expected to run on UI thread!
                                                                                                    	at com.facebook.react.bridge.SoftAssertions.assertCondition(SoftAssertions.java:37)
                                                                                                    	at com.facebook.react.bridge.UiThreadUtil.assertOnUiThread(UiThreadUtil.java:32)
                                                                                                    	at com.facebook.react.uimanager.UIManagerModule.resolveView(UIManagerModule.java:920)
                                                                                                    	at com.mrousavy.camera.CameraViewModule.findCameraView(CameraViewModule.kt:87)
                                                                                                    	at com.mrousavy.camera.CameraViewModule.access$findCameraView(CameraViewModule.kt:34)
                                                                                                    	at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:117)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2023-05-29 01:36:02.840 28542-28682 CameraView              com.client                           D  Found view 35!
2023-05-29 01:36:02.841 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:02.887 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:02.930 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:02.969 28542-1550  ReactNativeJS           com.client                           E  'startRecording:', { userInfo: null,
                                                                                                      message: 'An unknown error occurred while trying to start a video recording!',
                                                                                                      cause: 
                                                                                                       { stacktrace: 'java.lang.NullPointerException\n\tat com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:37)\n\tat com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:119)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)\n',
                                                                                                         message: null },
                                                                                                      code: 'capture/unknown' }
2023-05-29 01:36:03.034   388-4329  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:36:03.037 28542-4328  TrafficStats            com.client                           D  tagSocket(131) with statsTag=0xffffffff, statsUid=-1
2023-05-29 01:36:03.934 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:03.976 28542-28606 EGL_emulation           com.client                           D  app_time_stats: avg=61.09ms min=2.34ms max=692.57ms count=16
2023-05-29 01:36:04.135   388-4330  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:36:04.920  1282-1282  TaplEvents              com...le.android.apps.nexuslauncher  D  TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=764.95605, y[0]=2793.8794, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=22729876, downTime=22729876, deviceId=12, source=0x5002, displayId=0, eventId=567035516 }
2023-05-29 01:36:04.935 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:04.987 28542-28606 EGL_emulation           com.client                           D  app_time_stats: avg=1010.19ms min=1010.19ms max=1010.19ms count=1
2023-05-29 01:36:05.009  1282-1282  TaplEvents              com...le.android.apps.nexuslauncher  D  TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=764.95605, y[0]=2793.8794, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=22729965, downTime=22729876, deviceId=12, source=0x5002, displayId=0, eventId=214712046 }
2023-05-29 01:36:05.935 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:05.964  1282-1282  TaplEvents              com...le.android.apps.nexuslauncher  D  TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=652.93945, y[0]=2042.8589, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=22730920, downTime=22730920, deviceId=12, source=0x5002, displayId=0, eventId=44858335 }
2023-05-29 01:36:06.056  1282-1282  TaplEvents              com...le.android.apps.nexuslauncher  D  TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=652.93945, y[0]=2042.8589, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=22731012, downTime=22730920, deviceId=12, source=0x5002, displayId=0, eventId=327078664 }
2023-05-29 01:36:06.142   388-4333  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}
2023-05-29 01:36:06.934 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:06.987 28542-28606 EGL_emulation           com.client                           D  app_time_stats: avg=1000.08ms min=983.68ms max=1016.47ms count=2
2023-05-29 01:36:07.934 28542-1550  ReactNativeJS           com.client                           I  true
2023-05-29 01:36:07.988 28542-28606 EGL_emulation           com.client                           D  app_time_stats: avg=1000.47ms min=1000.47ms max=1000.47ms count=1
2023-05-29 01:36:08.147 28542-4336  TrafficStats            com.client                           D  tagSocket(116) with statsTag=0xffffffff, statsUid=-1
2023-05-29 01:36:08.148   388-4337  resolv                  netd                                 I  GetAddrInfoHandler::run: {100 100 100 983140 10159 0}

<galaxy S9>
//console
startRecording: {"cause": {"cause": {"message": "The video frame producer became inactive before any data was received.", "stacktrace": "java.lang.RuntimeException: The video frame producer became inactive before any data was received.
        at androidx.camera.video.Recorder.<clinit>(Recorder.java:269)
        at androidx.camera.video.Recorder$Builder.build(Recorder.java:2821)
        at com.mrousavy.camera.CameraView.configureSession(CameraView.kt:466)
        at com.mrousavy.camera.CameraView.access$configureSession(CameraView.kt:68)
        at com.mrousavy.camera.CameraView$update$1$1.invokeSuspend(CameraView.kt:327)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)     
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
"}, "message": "[capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized 
with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.", "stacktrace": "com.mrousavy.camera.InactiveSourceError: [capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.       
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized 
with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.
        at com.mrousavy.camera.CameraView_RecordVideoKt$startRecording$1.accept(CameraView+RecordVideo.kt:64)
        at com.mrousavy.camera.CameraView_RecordVideoKt$startRecording$1.accept(CameraView+RecordVideo.kt:52)
        at androidx.camera.video.Recorder$RecordingRecord.lambda$updateVideoRecordEvent$6$androidx-camera-video-Recorder$RecordingRecord(Recorder.java:2624)
        at androidx.camera.video.Recorder$RecordingRecord$$ExternalSyntheticLambda5.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.RuntimeException: The video frame producer became inactive before any data was received.
        at androidx.camera.video.Recorder.<clinit>(Recorder.java:269)
        at androidx.camera.video.Recorder$Builder.build(Recorder.java:2821)
        at com.mrousavy.camera.CameraView.configureSession(CameraView.kt:466)
        at com.mrousavy.camera.CameraView.access$configureSession(CameraView.kt:68)
        at com.mrousavy.camera.CameraView$update$1$1.invokeSuspend(CameraView.kt:327)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)     
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        ... 7 more
"}, "code": "capture/inactive-source", "message": "[capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized 
with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.", "userInfo": null}
```

### Device

Android 13 API 33 Pixel 3 XL, Android Galaxy S9

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by AgronnBajramii** [comment]
@JEONGEUN0204 did u manage to fix this? i am having the same error. adding the frame processor also makes the camera screen black and gives no error.

**Comment by JEONGEUN0204** [comment]
I couldn’t. So I’m using the native module

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
