### ISSUE TITLE
🐛 Property '_WORKLET' doesn't exist

### ISSUE THREAD

**Issue by fukemy** [cuvent/react-native-vision-camera#1613]
### What were you trying to do?

Hi, I  am trying to  implement custom processor

### Reproduceable Code

```
#import <Foundation/Foundation.h>
#import <VisionCamera/FrameProcessorPlugin.h>

@interface VISION_EXPORT_SWIFT_FRAME_PROCESSOR(beautifulFace, VisionFrameProcessorPlugin)
@end

*Swift*
@objc(VisionFrameProcessorPlugin)
public class VisionFrameProcessorPlugin: NSObject, FrameProcessorPluginBase {
    @objc
    public static func callback(_ frame: Frame!, withArgs args: [Any]!) -> Any! {
      guard let imageBuffer = CMSampleBufferGetImageBuffer(frame.buffer) else {
          return nil
      }
      ...
      return newFrame
    }
}
```

*babelconfig*
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ['react-native-reanimated/plugin',
    {
      globals: ['__beautifulFace'],
    },]
  ]
};
```

*decrale JS processor*
```
import type { Frame } from 'react-native-vision-camera';

declare let _WORKLET: true | undefined;


export function beautifulFace(frame : Frame) : Frame {
    'worklet';
    if (!_WORKLET) throw new Error('examplePluginSwift must be called from a frame processor!');
    return __beautifulFace(frame)
}
```

*useFrameProcessor*
```
const frameProcessor = useFrameProcessor((frame) => {
        'worklet';
        const paint = Skia.Paint()
        paint.setImageFilter
        paint.setColor(Skia.Color('red'))

        const rect = Skia.XYWHRect(400, 500, 100, 100)
        frame.drawRect(rect, paint)

        const result = beautifulFace()
        console.log('result')
    }, []);
```

### What happened instead?
```
2023-06-08 15:05:54.464218+0700 VedaxLink[86828:25596454] [javascript] Frame Processor threw an error: Property '_WORKLET' doesn't exist
In: ReferenceError: Property '_WORKLET' doesn't exist
        at beautifulFace (/Users/vedaxm1/Documents/Work/VedaxLink/utils/processor/VisionCameraProcessor.ts:1:36)
        at fn (native)
        at anonymous (/Users/vedaxm1/Documents/Work/VedaxLink/screen/call/GroupCallScreen.js:1:243)
        at fn (native)
        at anonymous (/Users/vedaxm1/Documents/Work/VedaxLink/node_modules/react-native-vision-camera/src/hooks/useFrameProcessor.ts:1:108)
```

Here is log
```
2023-06-08 15:22:40.879995+0700 VedaxLink[86870:25605389] Metal GPU Frame Capture Enabled
2023-06-08 15:22:40.880435+0700 VedaxLink[86870:25605389] Metal API Validation Enabled
2023-06-08 15:22:40.955832+0700 VedaxLink[86870:25605389] [native] [GESTURE HANDLER] Initialize gesture handler for view <RCTRootContentView: 0x11fe1a220; reactTag: 1; frame = (0 0; 390 844); gestureRecognizers = <NSArray: 0x2825540c0>; layer = <CALayer: 0x282b2fc40>>
2023-06-08 15:22:41.520639+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Installing Frame Processor Bindings for Bridge...
2023-06-08 15:22:41.520764+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Creating Worklet Context...
2023-06-08 15:22:41.524259+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Worklet Context Created!
2023-06-08 15:22:41.524360+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Installing Frame Processor plugins...
2023-06-08 15:22:41.524408+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Installing Frame Processor plugin "beautifulFace"...
2023-06-08 15:22:41.524467+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Frame Processor plugins installed!
2023-06-08 15:22:41.524501+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Installing global functions...
2023-06-08 15:22:41.524542+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Finished installing bindings.
2023-06-08 15:22:42.549403+0700 VedaxLink[86870:25605573] FrameProcessorBindings: Setting new frame processor...
2023-06-08 15:22:42.550948+0700 VedaxLink[86870:25605389] [native] [GESTURE HANDLER] Initialize gesture handler for view <RNSScreenView: 0x12711f6d0; reactTag: 4093; frame = (0 0; 390 844); autoresize = W+H; gestureRecognizers = <NSArray: 0x2827b18f0>; animations = { UIPacingAnimationForAnimatorsKey=<CABasicAnimation: 0x282a14b80>; position=<CASpringAnimation: 0x282a15980>; }; layer = <CALayer: 0x282a36840>>
2023-06-08 15:22:42.554563+0700 VedaxLink[86870:25605389] VisionCamera: Starting SkiaMetalCanvasProvider DisplayLink...
```

### Device

Iphone 12 

### VisionCamera Version

v3 rc

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by cauediademi** [comment]
same error here, using react-native-vision-camera#3.1.0

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by natemartins** [comment]
This is most definitely not a stale issue. @mrousavy I am beginning to see a pattern of you closing unresolved issues. 

I just got this same error 

```
Frame Processor threw an error: Property '_WORKLET' doesn't exist
```

I have searched everywhere and they all point to `react-native-vision-camera`

**Comment by mrousavy** [comment]
Sure @natemartins, if you want me to fix an error for you that does not reproduce in the Example app, I offer consultancy services billed by the hour. Email me if you're interested.

**Comment by xseignard** [comment]
@natemartins do you call the `react-native-reanimated` `runOnJS` on your frame processor?

**Comment by natemartins** [comment]
@xseignard Yes, I did. That was what threw the error

**Comment by Tamimjabr** [comment]
any updates? I have same issue using:     "react-native-vision-camera": "^3.3.1"

**Comment by xseignard** [comment]
@Tamimjabr same as above, I guess you use `react-native-reanimated` `runOnJS` on your frame processor
please switch to https://github.com/margelo/react-native-worklets-core

Use `const myFunctionJS = Worklets.createRunInJsFn(myFunction)` and then call `myFunctionJS` from the frame processor

**Comment by ChathuraLiyanapathirana** [comment]
> @Tamimjabr same as above, I guess you use `react-native-reanimated` `runOnJS` on your frame processor please switch to https://github.com/margelo/react-native-worklets-core
> 
> Use `const myFunctionJS = Worklets.createRunInJsFn(myFunction)` and then call `myFunctionJS` from the frame processor

life saver thanks a lot

**Comment by Driveemode** [comment]
> Use `const myFunctionJS = Worklets.createRunInJsFn(myFunction)` and then call `myFunctionJS` from the frame processor
Where `Worklets` imports from? not clear lol

**Comment by alaindimabuyo** [comment]
thanks for the tip @xseignard

**Comment by garyhogarth** [comment]
Just in case anyone does the same dumb thing I did. The createRunOnJS (old method deprecated) function needs to be created outside of the useFrameProcessor call.

> [@Tamimjabr](https://github.com/Tamimjabr) same as above, I guess you use `react-native-reanimated` `runOnJS` on your frame processor please switch to https://github.com/margelo/react-native-worklets-core
> 
> Use `const myFunctionJS = Worklets.createRunInJsFn(myFunction)` and then call `myFunctionJS` from the frame processor

**Comment by tarikfp** [comment]
If anyone is still looking for a solution, you can just use `useRunOnJS` from `react-native-worklets-core`

```

import { useRunOnJS } from "react-native-worklets-core";

const updateOCRJS = useRunOnJS(updateOCR, [updateOCR]);
const setProcessingStateJS = useRunOnJS(setProcessingState, [setProcessingState]);

// ... in frame processor:
setProcessingStateJS(true);
updateOCRJS(data);

```

**Comment by AlejandroCisnero** [comment]
This is what worked for me, Im not an expert in React Native, so if you find a room for improvement let me know

```javascript
import {
  useRef
} from 'react';
import {
  StyleSheet,
  Text,
  View
} from 'react-native';
import {
  Camera,
  useCameraDevice,
  useFrameProcessor
} from 'react-native-vision-camera';
import {
  Face,
  FaceDetectionOptions,
  useFaceDetector,
} from 'react-native-vision-camera-face-detector';
import { Worklets } from "react-native-worklets-core";
export default function App() {

  const faceDetectionOptions = useRef<FaceDetectionOptions>({
    // detection options
  }).current

  const handleDetectedFaces = (faces: Face[]) => {
    console.log('faces detected', faces)
  }

  const device = useCameraDevice('front')

  //IMPORTANT the creation of these two constants with the shared functions 
  //we want to use inside the frame processor later
  const detectFacesJs = Worklets.createRunOnJS(useFaceDetector(faceDetectionOptions).detectFaces);
  const handleDetectedFacesJs = Worklets.createRunOnJS(handleDetectedFaces);

  const frameProcessor = useFrameProcessor((frame) => {
      'worklet'
      try {
        detectFacesJs(frame).then((faces) => {
          handleDetectedFacesJs(faces);
        });
      } catch (error) {
        console.log(error);
      }
    }, [handleDetectedFacesJs])
  }

  return (
      <View style={{ flex: 1 }}>
        {!!device ? <Camera
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          frameProcessor={frameProcessor}
        /> : <Text>
          No Device
        </Text>}
      </View>
    )
}
```
