### ISSUE TITLE
🐛  [Android] - Camera does not work due to profile retreiving error

### ISSUE THREAD

**Issue by idrissakhi** [cuvent/react-native-vision-camera#1793]
### What's happening?

Opening the camera after giving permissions fails on android.

### Reproduceable Code

```tsx
import { ReactElement, useCallback, useEffect, useState } from 'react';
import { ImageRequireSource, Pressable, View, ViewStyle } from 'react-native';

import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, {
  Extrapolate,
  interpolate,
  useAnimatedProps,
  useAnimatedRef,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
  withTiming,
} from 'react-native-reanimated';

import { useSafeAreaInsets } from 'react-native-safe-area-context';
import {
  Camera,
  CameraDevice,
  CameraPosition,
  CameraProps,
  PhotoFile,
  TakePhotoOptions,
} from 'react-native-vision-camera';

import { filePrefix, isAndroid } from 'src/Shared/Constants';
import { useHapticEffect, usePrevious } from 'src/Shared/Hooks/Common';
import { HapticType } from 'src/Shared/NativeModules';
import { Color } from 'src/Shared/Types';
import { IconButton } from 'src/Shared/UI/Atoms';
import { FullScreenLoader } from 'src/Shared/UI/Molecules';

import { styles } from './CameraView.styles';

export interface CameraViewProps {
  onTakePhoto: (photo: PhotoFile) => void;
  testID?: string;
}

const flashIcon = new Map<TakePhotoOptions['flash'], ImageRequireSource>([
  ['auto', require('assets/icons/camera-flash-auto-icon/camera-flash-auto-icon.png')],
  ['on', require('assets/icons/camera-flash-on-icon/camera-flash-on-icon.png')],
  ['off', require('assets/icons/camera-flash-off-icon/camera-flash-off-icon.png')],
]);

/**
 * Returns next value for flash mode based on current, passed as argument
 *
 * @param flashMode - Current flash mode
 */
const getNextFlashMode = (flashMode: TakePhotoOptions['flash']): TakePhotoOptions['flash'] => {
  const flashModesOrder = Array.from(flashIcon.keys());
  const currentIndex = flashModesOrder.findIndex((mode) => mode === flashMode);
  if (currentIndex > -1) {
    return flashModesOrder[currentIndex >= flashModesOrder.length - 1 ? 0 : currentIndex + 1];
  }
  return flashModesOrder[0];
};

/**
 * Returns icon of flash mode
 *
 * @param flashMode - Flash mode to get icon for
 */
const getFlashModeIcon = (flashMode: TakePhotoOptions['flash']): ImageRequireSource => {
  return flashIcon.get(flashMode) ?? (flashIcon.get('auto') as ImageRequireSource);
};

const AnimatedCamera = Animated.createAnimatedComponent<CameraProps>(Camera);
Animated.addWhitelistedNativeProps({
  zoom: true,
});

export const CameraView = ({ onTakePhoto, testID = 'CameraView' }: CameraViewProps): ReactElement => {
  const { bottom: bottomInset } = useSafeAreaInsets();
  const { playHaptic } = useHapticEffect();

  const [devices, setDevices] = useState<{
    [key in CameraPosition]?: CameraDevice | undefined;
  }>({});
  const [cameraPosition, setCameraPosition] = useState<CameraPosition>('back');
  const [flash, setFlash] = useState<TakePhotoOptions['flash']>('auto');
  const [isPhotoBeingTaken, setIsPhotoBeingTaken] = useState(false);

  const cameraRef = useAnimatedRef<Camera>();
  const device = devices[cameraPosition];

  const fillScale = useSharedValue(0);

  useEffect(() => {
    (async () => {
      try {
        const available = await Camera.getAvailableCameraDevices();
        const actualDevices = {
          back: available.find((d) => d.position === 'back'),
          front: available.find((d) => d.position === 'front'),
        };
        setDevices(actualDevices);
      } catch (e) {
        console.warn(e);
      }
    })();
  }, []);

  // https://mrousavy.com/react-native-vision-camera/docs/guides/zooming
  const [minZoom, neutralZoom, maxZoom] = [device?.minZoom ?? 1, device?.neutralZoom ?? 1, device?.maxZoom ?? 1];

  const cameraZoom = useSharedValue(neutralZoom);

  // reset zoom value on change camera position
  const prevCameraPosition = usePrevious(cameraPosition);
  const resetCameraZoom = useCallback(() => {
    cameraZoom.value = withSpring(neutralZoom);
  }, [cameraZoom, neutralZoom]);

  useEffect(() => {
    if (prevCameraPosition !== cameraPosition) {
      resetCameraZoom();
    }
  }, [prevCameraPosition, cameraPosition, device, resetCameraZoom]);

  const animatedProps = useAnimatedProps<Partial<CameraProps>>(() => ({ zoom: cameraZoom.value }), [cameraZoom]);

  // Pinch to Zoom Gesture
  // The gesture handler maps the linear pinch gesture (0 - 1) to an exponential curve since a camera's zoom
  // function does not appear linear to the user. (aka zoom 0.1 -> 0.2 does not look equal in difference as 0.8 -> 0.9)
  const SCALE_FULL_ZOOM = 3;
  const startZoom = useSharedValue(0);
  const pinchGesture = Gesture.Pinch()
    .onStart((_) => {
      'worklet';
      startZoom.value = cameraZoom.value;
    })
    .onChange((event) => {
      'worklet';
      // we're trying to map the scale gesture to a linear zoom here
      const scale = interpolate(
        event.scale,
        [1 - 1 / SCALE_FULL_ZOOM, 1, SCALE_FULL_ZOOM],
        [-1, 0, 1],
        Extrapolate.CLAMP
      );
      cameraZoom.value = interpolate(scale, [-1, 0, 1], [minZoom, startZoom.value, maxZoom], Extrapolate.CLAMP);
    });

  const buttonFillAnimationStyle: ViewStyle = useAnimatedStyle(() => {
    'worklet';
    return {
      width: interpolate(fillScale.value, [0, 1], [0, 80]),
      height: interpolate(fillScale.value, [0, 1], [0, 80]),
      borderRadius: interpolate(fillScale.value, [0, 1], [0, 40]),
    };
  });

  const onFlashButtonPress = useCallback(() => {
    setFlash(getNextFlashMode(flash));
  }, [flash]);

  const onCameraPhotoButtonPress = useCallback(async () => {
    try {
      setIsPhotoBeingTaken(true);
      fillScale.value = withTiming(1, { duration: isAndroid ? 1250 : 125 });
      const cameraPhoto = await cameraRef.current?.takePhoto({ flash });
      if (cameraPhoto) {
        onTakePhoto({
          ...cameraPhoto,
          path: cameraPhoto.path?.startsWith(filePrefix) ? cameraPhoto.path : `${filePrefix}${cameraPhoto.path}`,
        });

        // proto preview is opened, reset zoom
        resetCameraZoom();
      }
    } catch (e) {
      console.warn(e);
    } finally {
      fillScale.value = 0;
      setIsPhotoBeingTaken(false);
    }
  }, [fillScale, cameraRef, flash, onTakePhoto, resetCameraZoom]);

  const canChangeCameraPosition = (['front', 'back'] as CameraPosition[]).every((position) => !!devices[position]);
  const canUseFlash = cameraPosition === 'back' && device?.hasFlash;

  const onChangeCameraPositionButtonPress = useCallback(() => {
    playHaptic(HapticType.Medium);
    setCameraPosition((prev) => (prev === 'front' ? 'back' : 'front'));
  }, [playHaptic]);

  if (device === null || device === undefined) {
    return <FullScreenLoader loaderColor={Color.Blue} overlayColor={Color.Black} />;
  }

  return (
    <>
      <GestureDetector gesture={pinchGesture}>
        <AnimatedCamera
          testID={`${testID}`}
          ref={cameraRef}
          style={styles.cameraView}
          device={device}
          isActive
          photo
          animatedProps={animatedProps}
          orientation="portrait"
          enableHighQualityPhotos
        />
      </GestureDetector>

      <View style={[styles.cameraButtonsContainer, { bottom: bottomInset + 40 }]}>
        {canUseFlash ? (
          <IconButton
            testID={`${testID}FlashButton`}
            icon={getFlashModeIcon(flash)}
            iconTestID={`${testID}FlashIcon${flash?.toUpperCase()}`}
            iconContainerStyle={[styles.cameraControlButton, styles.cameraControlLeftButton]}
            onPress={onFlashButtonPress}
          />
        ) : (
          <View
            testID={`${testID}LeftButtonPlaceholder`}
            style={[styles.cameraControlButtonPlaceholder, styles.cameraControlLeftButton]}
          />
        )}
        <Pressable
          testID={`${testID}TakePhotoButton`}
          style={styles.cameraControlTakePhotoButton}
          onPress={onCameraPhotoButtonPress}
          disabled={isPhotoBeingTaken}
        >
          <Animated.View
            testID={`${testID}TakePhotoButtonFill`}
            style={[{ backgroundColor: Color.White75 }, buttonFillAnimationStyle]}
          />
        </Pressable>
        {canChangeCameraPosition && (
          <IconButton
            testID={`${testID}CameraRotateButton`}
            icon={require('assets/icons/camera-rotate-icon/camera-rotate-icon.png')}
            onPress={onChangeCameraPositionButtonPress}
            iconContainerStyle={[styles.cameraControlButton, styles.cameraControlRightButton]}
          />
        )}
      </View>
    </>
  );
};
```

### Relevant log output

```shell
W/System.err: java.lang.RuntimeException: Error retrieving camcorder profile params
W/System.err:     at android.media.CamcorderProfile.native_get_camcorder_profile(Native Method)
W/System.err:     at android.media.CamcorderProfile.get(CamcorderProfile.java:528)
W/System.err:     at com.mrousavy.camera.extensions.CameraCharacteristics_getOutputSizesKt.getMaximumVideoSize(CameraCharacteristics+getOutputSizes.kt:46)
W/System.err:     at com.mrousavy.camera.extensions.CameraCharacteristics_getOutputSizesKt.getVideoSizes(CameraCharacteristics+getOutputSizes.kt:56)
W/System.err:     at com.mrousavy.camera.core.CameraDeviceDetails.getVideoSizes(CameraDeviceDetails.kt:129)
W/System.err:     at com.mrousavy.camera.core.CameraDeviceDetails.getFormats(CameraDeviceDetails.kt:138)
W/System.err:     at com.mrousavy.camera.core.CameraDeviceDetails.toMap(CameraDeviceDetails.kt:239)
W/System.err:     at com.mrousavy.camera.CameraViewModule$getAvailableCameraDevices$1.invokeSuspend(CameraViewModule.kt:149)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
W/ReactNativeJS: { [unknown/unknown: [unknown/unknown] Error retrieving camcorder profile params]
      name: 'unknown/unknown',
      _code: 'unknown/unknown',
      _message: '[unknown/unknown] Error retrieving camcorder profile params',
      _cause: undefined }
```

### Camera Device

```shell
[unknown/unknown: [unknown/unknown] Error retrieving camcorder profile params]
```

### Device

Samsung S20

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [ ] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by valn1** [comment]
im also having this issue in my samsung s20 +
vision camera v3 and bare minimum camera setup
```

const Scanner = (props: NavigationProps) => {
    const [device, setDevice] = useState(undefined as CameraDevice | undefined);
    const { hasPermission, requestPermission } = useCameraPermission();

    useEffect(() => {
        if (!hasPermission) {
            requestPermission().then(console.log).catch(console.warn);
            const devices = Camera.getAvailableCameraDevices(); //the error uccurs here(Error: Exception in HostObject::get for prop 'CameraDevices': java.lang.RuntimeException: Error retrieving camcorder profile params, js engine: hermes)
            setDevice(devices.find((d) => d.position === "back"));
        }
    }, []);

    return (
        <Screen>
            <Text>qrcode Scanner</Text>
            {hasPermission && device && <Camera style={StyleSheet.absoluteFill} device={device} isActive={true} />}
        </Screen>
    );
};

export default Scanner;

```

**Comment by valn1** [comment]
logcat:
```
--------- switch to main
09-28 12:01:42.173  2107  2407 E PaniGenerator: network is unknown.
09-28 12:01:42.185  2107  2407 E #IMSCR  : 09-28 12:01:42 0x1101000B:0,FILTERED ALL:11
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.747 14067 14144 E MediaProfiles: The given camcorder profile camera 4 quality 1 is not found
09-28 12:01:42.793 14067 14144 E ReactNativeJS: 'Error: Exception in HostObject::get for prop \'CameraDevices\': java.lang.RuntimeException: Error retrieving camcorder profile params, js engine: hermes', '\n    at Scanner (http://localhost:8081/src/screens/Scanner/index.bundle//&platform=android&app=br.ixcsoft.inmapsales&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:14:41)\n    at StaticContainer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:212523:17)\n    at EnsureSingleNavigator (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:208402:24)\n    at SceneView (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:212428:22)\n    at RCTView\n    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:59561:43)\n    at RCTView\n    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:59561:43)\n    at RCTView\n    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:59561:43)\n    at CardSheet (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:218563:23)\n    at RCTView\n    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:59561:43)\n    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:72616:62)\n    at PanGestureHandler (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:123199:38)\n    at PanGestureHandler (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:218644:34)\n    at RCTView\n    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:59561:43)\n    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:72616:62)\n    at RCTView\n    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:59561:43)\n    at Card (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:218049:36)\n    at CardContainer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:217670:34)\n    at RNSScreen\n    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:72616:62)\n    at Suspender (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:219264:22)\n    at Suspense\n    at Freeze (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:219283:23)\n    at DelayedFreeze (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:218808:22)\n    at InnerScreen (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inmapsales&modulesOnly=false&runModule=true:218857:36)\n    at Screen (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=br.ixcsoft.inm
09-28 12:01:42.802  2869  2869 E pageboostd: Received HALT command code 2
09-28 12:01:42.817 14067 14144 E ReactNativeJS: TypeError: Cannot read property 'CameraDevices' of undefined


```

**Comment by valn1** [comment]
i also got this:
```
09-28 12:16:39.955 17411 17411 E Berry_Drawer: getDrawerListName() : Exception : java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.samsung.accessory.hearablemgr.common.uhm.DeviceRegistryData.deviceId' on a null object reference in method 'java.lang.String com.samsung.accessory.hearablemgr.module.home.drawer.Drawer.getDrawerListName(com.samsung.accessory.hearablemgr.common.uhm.DeviceRegistryData, java.util.List)'

```

**Comment by valn1** [comment]
i found out that in the file "node_modules/react-native-vision-camera/src/CameraDevices.ts", NativeModules returns {} for some reason

**Comment by NiravSa** [comment]
+1

**Comment by mrousavy** [comment]
Hey - this should be fixed with the latest update in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by valn1** [comment]
the error is still happening after updating the lib.
any advice on how i can debug that and help fix this issue?

**Comment by valn1** [comment]
I tested in a Samsung s20 FE with nova launcher instead of oneui and it worked fine(only fails to switch back to back camera).
in my Samsung s20 plus, it didnt fails to get the camera device

**Comment by mrousavy** [comment]
That exact error? I am no longer using Camcorder, this sounds impossible...

Could you maybe create a new issue and paste the new logs you get in there?
Thanks!

**Comment by NiravSa** [comment]
I was having the same error on the latest version. not able to load the camera device. I also got a runtime error when trying to load a camera

**Comment by mrousavy** [comment]
Ahh, my bad! I oversaw this. Check this PR out and let me know if that works for you: https://github.com/mrousavy/react-native-vision-camera/pull/1907
