### ISSUE TITLE
🐛 Cannot switch to 'back' camera device on Android 

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#1863]
### What's happening?

When select and set first camera device with position === 'back' on Samsung S21+ then app crash with error:
`FATAL EXCEPTION: mrousavy/VisionCamera.main`

PS. Device has many pixelFormat items duplicates with the only diff of "photoHeight" value and that is not good.

### Reproduceable Code

```tsx
getBackDevice = (devices) => {
    const backCameras = devices.filter((d) => {
      return d.position === "back";
    });

    return backCameras[0];
  }
```

### Relevant log output

```shell
`FATAL EXCEPTION: mrousavy/VisionCamera.main
                                                                                                    Process: com.myapp, PID: 26862
                                                                                                    java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
                                                                                                    	at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:765)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1289)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1345)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:313)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.updateRepeatingRequest(CameraSession.kt:577)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.startRunning(CameraSession.kt:555)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.access$startRunning(CameraSession.kt:49)
                                                                                                    	at com.mrousavy.camera.core.CameraSession$configureFormat$1.invokeSuspend(CameraSession.kt:200)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@69ff6ca, mrousavy/VisionCamera.main]`
```

### Camera Device

```json
LOG  cameraDevice {
  "formats": [
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 3024,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 4032,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 2268,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 4032,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1816,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 4032,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 3024,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 3024,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 2160,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 3840,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1080,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 2400,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1440,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 1920,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1080,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 1920,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 864,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 3024,
      "videoHeight": 3024,
      "photoWidth": 1920,
      "fieldOfView": 67.80220189063854,
      "maxFps": 30
    },
    // Device has many pixelFormat items duplicates with the only diff of "photoHeight" value
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 360,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 256,
      "videoHeight": 144,
      "photoWidth": 640,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 288,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 256,
      "videoHeight": 144,
      "photoWidth": 352,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 240,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 256,
      "videoHeight": 144,
      "photoWidth": 320,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 3024,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 4032,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 2268,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 4032,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1816,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 4032,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 3024,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 3024,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 2160,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 3840,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1080,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 2400,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1440,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 1920,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1080,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 1920,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 864,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 1920,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1080,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 1440,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 1088,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 1088,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 720,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 1280,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 720,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 960,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 480,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 720,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 480,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 640,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 360,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 640,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 288,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 352,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    },
    {
      "pixelFormats": [
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "off",
        "cinematic-extended"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": true,
      "photoHeight": 240,
      "supportsVideoHDR": false,
      "supportsDepthCapture": false,
      "maxISO": 3200,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 176,
      "videoHeight": 144,
      "photoWidth": 320,
      "fieldOfView": 67.80220189063854,
      "maxFps": 60
    }
  ],
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "supportsLowLightBoost": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Samsung S21+

### VisionCamera Version

3.1.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by bglgwyng** [comment]
It's a duplication of #1773 but it's reassuring to see that the behavior is reproduced in the example app!

**Comment by Romick2005** [comment]
Adding [key](https://github.com/mrousavy/react-native-vision-camera/issues/1773#issuecomment-1710524501) to the Camera component fix the issue.
