### ISSUE TITLE
🐛 Internal `getPlanes` crash for rgb while using frame processors

### ISSUE THREAD

**Issue by rodgomesc** [cuvent/react-native-vision-camera#1876]
### What's happening?

after implementing #1875 i noticed the following runtime crash that throws  at `com.mrousavy.camera.frameprocessor.Frame.getPlanesCount(Frame.java:83)`

### Reproduceable Code

```tsx
call any function that tries to use getPlanes under the hoods or directly


  @SuppressLint("SuspiciousIndentation")
  override fun callback(@NotNull frame: Frame, @Nullable params: Map<String, Any>?): Any? {



    val buffer = frame.toByteBuffer();



    val map = hashMapOf<String, Any>(
      "example_str" to "Test",
      "example_bool" to true,
      "example_double" to 5.3
    )

    val array = arrayListOf<Any>(
      "Hello!",
      true,
      17.38
    )

    map["example_array"] = array
    return map
  }

}
```

### Relevant log output

```shell
RGBA override BLOB format buffer should have height == width
2023-09-27 15:15:15.933  9799-9929  ervisionexampl          com.gamersafervisionexample          A  runtime.cc:659] Runtime aborting...
runtime.cc:659] Dumping all threads without mutator lock held
runtime.cc:659] All threads:
runtime.cc:659] DALVIK THREADS (42):
runtime.cc:659] "mrousavy/VisionCamera.video" prio=5 tid=37 Runnable
runtime.cc:659]   | group="" sCount=0 dsCount=0 flags=0 obj=0x13c03960 self=0xb400007ad69f4400
runtime.cc:659]   | sysTid=9929 nice=0 cgrp=default sched=0/0 handle=0x7c0d382cc0
runtime.cc:659]   | state=R schedstat=( 144460510 51072293 215 ) utm=14 stm=0 core=4 HZ=100
runtime.cc:659]   | stack=0x7c0d27f000-0x7c0d281000 stackSize=1043KB
runtime.cc:659]   | held mutexes= "abort lock" "mutator lock"(shared held)
runtime.cc:659]   native: #00 pc 000000000047c188  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
runtime.cc:659]   native: #01 pc 0000000000581444  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+380)
runtime.cc:659]   native: #02 pc 000000000059e288  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
runtime.cc:659]   native: #03 pc 0000000000597c2c  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+536)
runtime.cc:659]   native: #04 pc 0000000000596cb4  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1928)
runtime.cc:659]   native: #05 pc 0000000000533b58  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1896)
runtime.cc:659]   native: #06 pc 000000000001394c  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
runtime.cc:659]   native: #07 pc 0000000000006d10  /system/lib64/liblog.so (__android_log_assert+336)
runtime.cc:659]   native: #08 pc 000000000000164c  /system/lib64/libmedia_jni_utils.so (android::getLockedImageInfo(android::CpuConsumer::LockedBuffer*, int, int, unsigned char**, unsigned int*, int*, int*)+1292)
runtime.cc:659]   native: #09 pc 000000000003d330  /system/lib64/libmedia_jni.so (Image_createSurfacePlanes(_JNIEnv*, _jobject*, int, int)+616)
runtime.cc:659]   at android.media.ImageReader$SurfaceImage.nativeCreatePlanes(Native method)
runtime.cc:659]   - locked <0x0c1d53ac> (a android.media.ImageReader$SurfaceImage)
runtime.cc:659]   at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:926)
runtime.cc:659]   at com.mrousavy.camera.frameprocessor.Frame.getPlanesCount(Frame.java:83)
runtime.cc:659]   at com.mrousavy.camera.core.VideoPipeline.getImageReader$lambda$2(VideoPipeline.kt:145)
runtime.cc:659]   at com.mrousavy.camera.core.VideoPipeline.$r8$lambda$RBt5oiVcrkwyTbFDf1xzJJfIdPg(VideoPipeline.kt:-1)
runtime.cc:659]   at com.mrousavy.camera.core.VideoPipeline$$ExternalSyntheticLambda0.onImageAvailable(D8$$SyntheticClass:-1)
runtime.cc:659]   at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:826)
runtime.cc:659]   at android.os.Handler.dispatchMessage(Handler.java:106)
runtime.cc:659]   at android.os.Looper.loop(Looper.java:236)
runtime.cc:659]   at android.os.HandlerThread.run(HandlerThread.java:67)
runtime.cc:659] 
runtime.cc:659] "main" prio=7 tid=1 Native
runtime.cc:659]   | group="" sCount=2 dsCount=0 flags=1 obj=0x716b0bd8 self=0xb400007ca6cb5c00
runtime.cc:659]   | sysTid=9799 nice=-4 cgrp=default sched=0/0 handle=0x7ca83524f8
runtime.cc:659]   | state=S schedstat=( 2221437920 359466202 2881 ) utm=204 stm=17 core=6 HZ=100
runtime.cc:659]   | stack=0x7ff8368000-0x7ff836a000 stackSize=8192KB
runtime.cc:659]   | held mutexes=
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "name": "FRONT (1)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "front",
  "id": "1"
}
```

### Device

Android 11 / Mi 9T pro

### VisionCamera Version

3.1.0 with #1875 applied

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by rodgomesc** [comment]
solved in #1875
