### ISSUE TITLE
🐛 App closes unexpectedly after recording a video

### ISSUE THREAD

**Issue by igperez-ar** [cuvent/react-native-vision-camera#1903]
### What's happening?

Seconds after recording a video, the app quits unexpectedly with no visible errors.

### Reproduceable Code

```tsx
import React, { useRef, useState } from 'react';
import { StyleSheet, View, TouchableOpacity } from 'react-native';
import { Camera, useCameraDevice } from 'react-native-vision-camera';

const CameraScreen = () => {
  const device = useCameraDevice('front');
  const camera = useRef<Camera>(null);
  const [isRecording, setIsRecording] = useState(false);

  const recordVideo = () => {
    camera.current?.startRecording({
      flash: 'off',
      onRecordingFinished: () => console.log('finish'),
      onRecordingError: (e) => console.log(e),
      fileType: 'mp4',
    });
  };

  const onPressTakeVideo = async () => {
    if (!isRecording) {
      recordVideo();
    } else {
      await camera.current?.stopRecording();
    }
    setIsRecording(!isRecording);
  };

  if (!device) {
    return <View />;
  }

  return (
    <View style={{ flex: 1 }}>
      <Camera
        ref={camera}
        style={StyleSheet.absoluteFill}
        enableZoomGesture={false}
        video
        orientation="portrait"
        device={device}
        isActive
      />
      <TouchableOpacity
        style={{
          height: 50,
          width: '100%',
          backgroundColor: 'green',
          bottom: 0,
          position: 'absolute',
        }}
        onPress={onPressTakeVideo}
      />
    </View>
  );
};

export default CameraScreen;
```

### Relevant log output

```shell
2023-10-02 09:58:27.002  9634-9634  VideoPipeline           app.debug                            I  Rendering to RecordingSession..
2023-10-02 09:58:27.035  9634-9634  CameraView              app.debug                            D  Finding view 753...
2023-10-02 09:58:27.036  9634-9634  CameraView              app.debug                            D  Found view 753!
2023-10-02 09:58:27.036  9634-10101 RecordingSession        app.debug                            I  Stopping RecordingSession..
2023-10-02 09:58:27.040  9634-9634  VideoPipeline           app.debug                            I  Rendering to RecordingSession..
2023-10-02 09:58:27.069  9634-9634  VideoPipeline           app.debug                            I  Rendering to RecordingSession..
2023-10-02 09:58:27.077  9634-9634  RecordingSession        app.debug                            I  MediaRecorder Info: 268436456 (-1011)
2023-10-02 09:58:27.102  9634-9634  VideoPipeline           app.debug                            I  Rendering to RecordingSession..
2023-10-02 09:58:27.130  9634-10101 VideoPipeline           app.debug                            I  Setting 1800 x 1600 RecordingSession Output...
2023-10-02 09:58:27.130  9634-10101 OpenGLRenderer          app.debug                            I  Destroying OpenGL Surface...
2023-10-02 09:58:27.131  9634-10101 VideoPipeline           app.debug                            I  Setting 1800 x 1600 FrameProcessor Output...
2023-10-02 09:58:27.198  9634-9634  app.debug               app.debug                            W  Accessing hidden method Landroid/view/Window;->getInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
2023-10-02 09:58:27.202  9634-9634  unknown:ReactModalHost  app.debug                            E  Creating new dialog from context: app.MainActivity@2552e1d@39136797
2023-10-02 09:58:27.267  9634-9634  unknown:ReactModalHost  app.debug                            E  Updating existing dialog with context: app.MainActivity@2552e1d@39136797
2023-10-02 09:58:38.596  9634-9649  StrictMode              app.debug                            D  StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                                    	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1892)
                                                                                                    	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
                                                                                                    	at android.view.Surface.finalize(Surface.java:242)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
                                                                                                    	at java.lang.Daemons$Daemon.run(Daemons.java:137)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
                                                                                                    Caused by: java.lang.Throwable: Explicit termination method 'release' not called
                                                                                                    	at dalvik.system.CloseGuard.open(CloseGuard.java:237)
                                                                                                    	at android.view.Surface.setNativeObjectLocked(Surface.java:650)
                                                                                                    	at android.media.MediaCodec.native_createPersistentInputSurface(Native Method)
                                                                                                    	at android.media.MediaCodec.createPersistentInputSurface(MediaCodec.java:2059)
                                                                                                    	at com.mrousavy.camera.core.RecordingSession.<init>(RecordingSession.kt:44)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:292)
                                                                                                    	at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:51)
                                                                                                    	at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:88)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-10-02 09:58:38.596  9634-9649  System.err              app.debug                            W  StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
2023-10-02 09:58:38.597  9634-9649  Process                 app.debug                            I  Sending signal. PID: 9634 SIG: 9
2023-10-02 09:58:38.668  1984-2477  InputDispatcher         system_server                        E  channel 'a2c4b24 app.debug/app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
---------------------------- PROCESS ENDED (9634) for package app.debug ----------------------------
2023-10-02 09:58:38.774  1984-2477  InputDispatcher         system_server                        E  channel '537547d app.debug/app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2023-10-02 09:58:38.796  1984-5365  InputDispatcher         system_server                        E  Window handle Window{a2c4b24 u0 app.debug/app.MainActivity} has no registered input channel
2023-10-02 09:58:38.796  1984-5365  InputDispatcher         system_server                        E  Window handle Window{537547d u0 app.debug/app.MainActivity} has no registered input channel
2023-10-02 09:58:38.812  1984-3869  InputDispatcher         system_server                        E  Window handle Window{a2c4b24 u0 app.debug/app.MainActivity} has no registered input channel
2023-10-02 09:58:38.986  1015-2141  BufferQueueProducer     surfaceflinger                       E  [SurfaceView - app.debug/app.MainActivity#0] cancelBuffer: BufferQueue has been abandoned
2023-10-02 09:58:38.987  1015-2141  BufferQueueProducer     surfaceflinger                       E  [SurfaceView - app.debug/app.MainActivity#0] cancelBuffer: BufferQueue has been abandoned
2023-10-02 09:58:38.989  1015-2141  BufferQueueProducer     surfaceflinger                       E  [SurfaceView - app.debug/app.MainActivity#0] cancelBuffer: BufferQueue has been abandoned
2023-10-02 09:58:38.989  1015-2141  BufferQueueProducer     surfaceflinger                       E  [SurfaceView - app.debug/app.MainActivity#0] cancelBuffer: BufferQueue has been abandoned
2023-10-02 09:58:38.990  1015-2141  BufferQueueProducer     surfaceflinger                       E  [SurfaceView - app.debug/app.MainActivity#0] cancelBuffer: BufferQueue has been abandoned
2023-10-02 09:58:38.990  1015-2141  BufferQueueProducer     surfaceflinger                       E  [SurfaceView - app.debug/app.MainActivity#0] cancelBuffer: BufferQueue has been abandoned
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "name": "FRONT (1)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "front",
  "id": "1"
}
```

### Device

Motorola G8 Plus - Android 10

### VisionCamera Version

3.1.0 - 3.2.2

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Huh, that's weird! The only error I can read in your logs is that some `release()` method is not called, but I am calling it here: https://github.com/mrousavy/react-native-vision-camera/blob/554b7416b115d6d4f88c2ac749e0155c1e9494e4/package/android/src/main/java/com/mrousavy/camera/core/RecordingSession.kt#L103

Maybe I need to release something else? 🤔

**Comment by mrousavy** [comment]
Ah - could you maybe try swapping those two lines and try again? https://github.com/mrousavy/react-native-vision-camera/blob/554b7416b115d6d4f88c2ac749e0155c1e9494e4/package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt#L302-L303

**Comment by mrousavy** [comment]
No reply within 2 weeks, closing
