### ISSUE TITLE
🔧 Example app is giving babel bundling error 

### ISSUE THREAD

**Issue by nateshmbhat** [cuvent/react-native-vision-camera#1951]
### How were you trying to build the app?

i tried running the example app. it builds fine on ios but when bundling using metro bundle, i'm getting this error : 

Node found at: /Users/natesh.bhat/.nvm/versions/node/v16.18.1/bin/node

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒

Error while reading cache, falling back to a full crawl:
 Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at deserialize (node:v8:380:7)
    at DiskCacheManager.read (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/cache/DiskCacheManager.js:53:33)
    at HasteMap.read (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/index.js:356:39)
    at /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/index.js:290:36
    at HasteMap.build (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/index.js:341:9)
    at new DependencyGraph (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/node-haste/DependencyGraph.js:60:8)
    at new Bundler (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/Bundler.js:18:22)
    at new IncrementalBundler (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/IncrementalBundler.js:35:21)
    at new Server (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/Server.js:77:21)
    at runMetro (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/index.flow.js:59:18)
                Welcome to Metro v0.76.7
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

```

transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/App.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/PermissionsPage.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/CameraPage.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/CameraPage.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/DevicesPage.tsx.
 BUNDLE  ./index.js 

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/CameraError.ts: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../node_modules
  ../../../node_modules
  ../../../../../node_modules
> 1 | export type PermissionError = 'permission/microphone-permission-denied' | 'permission/camera-permission-denied'
  2 | export type ParameterError =
  3 |   | 'parameter/invalid-parameter'
  4 |   | 'parameter/unsupported-output'
    at ModuleResolver.resolveDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/frame-processors/ExamplePlugin.ts.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/views/CaptureButton.tsx.
```

### Full build logs

```tsx
Node found at: /Users/natesh.bhat/.nvm/versions/node/v16.18.1/bin/node

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


Error while reading cache, falling back to a full crawl:
 Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at deserialize (node:v8:380:7)
    at DiskCacheManager.read (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/cache/DiskCacheManager.js:53:33)
    at HasteMap.read (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/index.js:356:39)
    at /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/index.js:290:36
    at HasteMap.build (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro-file-map/src/index.js:341:9)
    at new DependencyGraph (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/node-haste/DependencyGraph.js:60:8)
    at new Bundler (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/Bundler.js:18:22)
    at new IncrementalBundler (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/IncrementalBundler.js:35:21)
    at new Server (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/Server.js:77:21)
    at runMetro (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/index.flow.js:59:18)
                Welcome to Metro v0.76.7
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android





transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/App.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/PermissionsPage.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/CameraPage.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/CameraPage.tsx.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/DevicesPage.tsx.
 BUNDLE  ./index.js 

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/CameraError.ts: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../node_modules
  ../../../node_modules
  ../../../../../node_modules
> 1 | export type PermissionError = 'permission/microphone-permission-denied' | 'permission/camera-permission-denied'
  2 | export type ParameterError =
  3 |   | 'parameter/invalid-parameter'
  4 |   | 'parameter/unsupported-output'
    at ModuleResolver.resolveDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/frame-processors/ExamplePlugin.ts.
transform[stderr]: Could not resolve "/Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/src/index" in file /Users/natesh.bhat/Desktop/isha/react-native-vision-camera/package/example/src/views/CaptureButton.tsx.
```

### Project dependencies

```json
{
  "name": "react-native-vision-camera-example",
  "description": "Example app for react-native-vision-camera",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "pods": "cd ios && pod install",
    "lint": "eslint . --fix",
    "lint-ci": "yarn lint -f ../node_modules/@firmnav/eslint-github-actions-formatter/dist/formatter.js",
    "typescript": "tsc --noEmit"
  },
  "dependencies": {
    "@react-native-camera-roll/camera-roll": "^5.7.2",
    "@react-native-community/blur": "^4.3.2",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "react": "^18.2.0",
    "react-native": "^0.72.3",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-mmkv": "^2.10.2",
    "react-native-pressable-opacity": "^1.0.10",
    "react-native-reanimated": "^3.5.4",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.24.0",
    "react-native-static-safe-area-insets": "^2.2.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-video": "^5.2.1",
    "react-native-worklets-core": "^0.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.10",
    "@babel/preset-env": "^7.22.10",
    "@babel/runtime": "^7.23.1",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.9",
    "@react-native/typescript-config": "^0.73.0",
    "@types/react": "^18.2.19",
    "@types/react-native-vector-icons": "^6.4.13",
    "@types/react-native-video": "^5.0.15",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.46.0",
    "eslint-plugin-prettier": "^5.0.0",
    "metro-react-native-babel-preset": "^0.77.0",
    "prettier": "^3.0.1",
    "typescript": "^5.1.6"
  }
}
```

### VisionCamera Version

Commit id : 6e72781 (main branch)

### Target platforms

iOS, Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

No, I cannot build the Example app either

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
It builds for me.

**Comment by IvanByRool** [comment]
Same here, 
xcode 14.3
iphone 13 / 16.6.1
thx

**Comment by IvanByRool** [comment]
To be more precise, 
it's building, but getting this error when the app launches
Tested with xcode 15 & iphone 13 / 16.6.1
Example app (no changes)

**Comment by mrousavy** [comment]
Yea try with Xcode 15. This should normally build, if not there's an issue with your machine.

In the CI here it also builds.
