### ISSUE TITLE
🐛 Android front camera seems to not work after 3.6

### ISSUE THREAD

**Issue by angelos3lex** [cuvent/react-native-vision-camera#2075]
### What's happening?

Black screen when using front camera, on android.
Also i get weird logs about camera disconnection:
```
 Camera onError:  [session/camera-has-been-disconnected: [session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: DISCONNECTED]
 WARN  Camera onError:  [unknown/unknown: [unknown/unknown] CameraDevice was already closed]
```

### Reproduceable Code

```tsx
const device = useCameraDevice('front');
const format = useCameraFormat(device, [{videoResolution: {width: 1920, height: 1080}, fps: 30}]);

if (!device) {
  return <></>;
}    

return (
  <Camera
    key={device.id}
    ref={props.cameraRef}
    style={props.style}
    video={true}
    audio={false}
    onError={props.onError}
    device={device}
    isActive={true}
    fps={30}
    format={format}
    resizeMode="contain"
    onInitialized={onCameraReady}
  />
)
```

### Relevant log output

```shell
I  Legacy camera service transitioning to state ERROR
2023-10-24 17:36:48.103  1759-7112  CameraManagerGlobal     com.android.systemui                 I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.package.name API Level 1
2023-10-24 17:36:48.103  2910-2929  CameraManagerGlobal     com.sec.android.sdhms                I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.package.name API Level 1
2023-10-24 17:36:48.103 22508-22585 CameraManagerGlobal     com.package.name                   I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.package.name API Level 1
2023-10-24 17:36:48.606   868-18567 CameraService           cameraserver                         I  finishCameraOps: Finish camera ops, package name = com.package.name, client UID = 11583
2023-10-24 17:36:48.610  2910-2929  CameraManagerGlobal     com.sec.android.sdhms                I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.package.name API Level 1
2023-10-24 17:36:48.610 22508-22585 CameraManagerGlobal     com.package.name                   I  postSingleUpdate device: camera id 0 status STATUS_PRESENT
2023-10-24 17:36:48.611  1759-7112  CameraManagerGlobal     com.android.systemui                 I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.package.name API Level 1
2023-10-24 17:36:48.611 22508-22894 CameraDevices           com.package.name                   I  Camera #0: Available!
2023-10-24 17:36:48.612 22508-22585 CameraManagerGlobal     com.package.name                   I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.package.name API Level 1
2023-10-24 17:36:48.615   868-18567 CameraService           cameraserver                         I  service.camera.client set to com.package.name
2023-10-24 17:36:48.615   868-18567 CameraService           cameraserver                         I  startCameraOps: Start camera ops, package name = com.package.name, client UID = 11583
2023-10-24 17:36:48.619 22508-22585 CameraManagerGlobal     com.package.name                   I  postSingleUpdate device: camera id 1 status STATUS_NOT_AVAILABLE
2023-10-24 17:36:48.620 22508-22894 CameraDevices           com.package.name                   I  Camera #1: Unavailable!
2023-10-24 17:36:48.621  2910-2929  CameraManagerGlobal     com.sec.android.sdhms                I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.package.name API Level 1
2023-10-24 17:36:48.621  1759-7112  CameraManagerGlobal     com.android.systemui                 I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.package.name API Level 1
2023-10-24 17:36:48.622 22508-22585 CameraManagerGlobal     com.package.name                   I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.package.name API Level 1
2023-10-24 17:36:48.731 22508-23999 CameraManager           com.package.name                   I  Camera 0: Opened!
2023-10-24 17:36:48.731 22508-23999 CameraManager           com.package.name                   I  Camera 0: Disconnected!
2023-10-24 17:36:48.737 22508-23999 CameraManager           com.package.name                   I  Camera 1: Opened!
2023-10-24 17:36:48.751 22508-23999 PreviewView             com.package.name                   I  Resizing PreviewView to 1024 x 768...
2023-10-24 17:36:48.751 22508-23999 CameraSession           com.package.name                   I  Successfully configured Camera #0!
2023-10-24 17:36:48.761 22508-23999 CameraSession           com.package.name                   I  Configuring Session for Camera #0...
2023-10-24 17:36:48.764 22508-23999 CameraSession           com.package.name                   I  Adding 1472 x 1104 Video Output in Format #34...
2023-10-24 17:36:48.778 22508-23999 VideoPipeline           com.package.name                   I  Initializing 1472 x 1104 Video Pipeline (format: NATIVE)
2023-10-24 17:36:48.793 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 0: Creating Capture Session #1000... Hardware Level: 2} | Outputs: [android.hardware.camera2.params.OutputConfiguration@e8750dd0]
2023-10-24 17:36:48.794 22508-23999 CreateCaptureSession    com.package.name                   I  Using new API (>=28)
2023-10-24 17:36:48.797 22508-23999 CameraSession           com.package.name                   E  Failed to configure CameraSession! Error: CameraDevice was already closed, Config-Diff: Difference(deviceChanged=true, outputsChanged=true, sidePropsChanged=true)
                                                                                                    java.lang.IllegalStateException: CameraDevice was already closed
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2550)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:648)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:634)
                                                                                                    	at com.mrousavy.camera.extensions.CameraDevice_createCaptureSessionKt.createCaptureSession(CameraDevice+createCaptureSession.kt:57)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.configureOutputs(CameraSession.kt:356)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.configure(CameraSession.kt:136)
                                                                                                    	at com.mrousavy.camera.core.CameraSession$configure$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:237)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-10-24 17:36:48.797 22508-23999 CameraView              com.package.name                   E  invokeOnError(...):
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  java.lang.IllegalStateException: CameraDevice was already closed
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2550)
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:648)
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:634)
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.extensions.CameraDevice_createCaptureSessionKt.createCaptureSession(CameraDevice+createCaptureSession.kt:57)
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.core.CameraSession.configureOutputs(CameraSession.kt:356)
2023-10-24 17:36:48.798 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.core.CameraSession.configure(CameraSession.kt:136)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.core.CameraSession$configure$1.invokeSuspend(Unknown Source:15)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at android.os.Handler.handleCallback(Handler.java:883)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at android.os.Handler.dispatchMessage(Handler.java:100)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at android.os.Looper.loop(Looper.java:237)
2023-10-24 17:36:48.799 22508-23999 System.err              com.package.name                   W  	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-10-24 17:36:48.817 22508-23999 PreviewView             com.package.name                   I  Resizing PreviewView to 1024 x 768...
2023-10-24 17:36:48.818 22508-23999 CameraSession           com.package.name                   I  Successfully configured Camera #1!
2023-10-24 17:36:48.826 22508-23999 CameraSession           com.package.name                   I  Configuring Session for Camera #1...
2023-10-24 17:36:48.828 22508-23999 CameraSession           com.package.name                   I  Adding 1472 x 1104 Video Output in Format #34...
2023-10-24 17:36:48.828 22508-23999 VideoPipeline           com.package.name                   I  Initializing 1472 x 1104 Video Pipeline (format: NATIVE)
2023-10-24 17:36:48.838 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 1: Creating Capture Session #1001... Hardware Level: 2} | Outputs: [android.hardware.camera2.params.OutputConfiguration@818293af]
2023-10-24 17:36:48.838 22508-23999 CreateCaptureSession    com.package.name                   I  Using new API (>=28)
2023-10-24 17:36:48.842 22508-23999 CameraDeviceState       com.package.name                   I  Legacy camera service transitioning to state CONFIGURING
2023-10-24 17:36:48.843 22508-24076 RequestThread-1         com.package.name                   I  Configure outputs: 1 surfaces configured.
2023-10-24 17:36:48.843 22508-24076 Camera                  com.package.name                   D  app passed NULL surface
2023-10-24 17:36:48.883 22508-24077 libc                    com.package.name                   E  Access denied finding property "persist.camera.legacy_perf"
2023-10-24 17:36:48.889 22508-23999 CameraDeviceState       com.package.name                   I  Legacy camera service transitioning to state IDLE
2023-10-24 17:36:48.891 22508-23999 CameraSession           com.package.name                   I  Updating CameraSession Configuration...
2023-10-24 17:36:48.892 22508-23999 CameraSession           com.package.name                   I  Configuring Camera #0...
2023-10-24 17:36:48.893 22508-23999 CameraManager           com.package.name                   I  Camera 0: Opening...
2023-10-24 17:36:48.905 22508-23999 CameraManager           com.package.name                   I  Using legacy camera HAL.
2023-10-24 17:36:48.907   868-1785  CameraService           cameraserver                         I  CameraService::connect call (PID -1 "com.package.name", camera ID 0) for HAL version default and Camera API version 1
2023-10-24 17:36:48.908   868-1785  CameraService           cameraserver                         I  CameraService::validateClientPermissionsLocked is ok : calling pid 22508, calling uid 11583, client com.package.name , cameraservice pid=868, device user 0, currently allowed device users: 0
2023-10-24 17:36:48.909 22508-24036 Camera                  com.package.name                   E  Error 2
2023-10-24 17:36:48.909 22508-24036 RequestThread-1         com.package.name                   I  Flushing all pending requests.
2023-10-24 17:36:48.909 22508-24036 RequestQueue            com.package.name                   E  cancel failed: no repeating request exists.
2023-10-24 17:36:48.909 22508-24036 CameraDeviceState       com.package.name                   I  Legacy camera service transitioning to state ERROR
2023-10-24 17:36:48.910  1759-6844  CameraManagerGlobal     com.android.systemui                 I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.package.name API Level 1
2023-10-24 17:36:48.910 22508-22585 CameraManagerGlobal     com.package.name                   I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.package.name API Level 1
2023-10-24 17:36:48.910  2910-2927  CameraManagerGlobal     com.sec.android.sdhms                I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.package.name API Level 1
2023-10-24 17:36:48.938   868-1785  CameraService           cameraserver                         I  finishCameraOps: Finish camera ops, package name = com.package.name, client UID = 11583
2023-10-24 17:36:48.939  1759-6844  CameraManagerGlobal     com.android.systemui                 I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.package.name API Level 1
2023-10-24 17:36:48.940 22508-22585 CameraManagerGlobal     com.package.name                   I  postSingleUpdate device: camera id 1 status STATUS_PRESENT
2023-10-24 17:36:48.940 22508-22894 CameraDevices           com.package.name                   I  Camera #1: Available!
2023-10-24 17:36:48.940  2910-2927  CameraManagerGlobal     com.sec.android.sdhms                I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.package.name API Level 1
2023-10-24 17:36:48.940 22508-22585 CameraManagerGlobal     com.package.name                   I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.package.name API Level 1
2023-10-24 17:36:48.943   868-1785  CameraService           cameraserver                         I  service.camera.client set to com.package.name
2023-10-24 17:36:48.943   868-1785  CameraService           cameraserver                         I  startCameraOps: Start camera ops, package name = com.package.name, client UID = 11583
2023-10-24 17:36:48.948  1759-7112  CameraManagerGlobal     com.android.systemui                 I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.package.name API Level 1
2023-10-24 17:36:48.948 22508-22585 CameraManagerGlobal     com.package.name                   I  postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
2023-10-24 17:36:48.948  2910-2929  CameraManagerGlobal     com.sec.android.sdhms                I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.package.name API Level 1
2023-10-24 17:36:48.948 22508-22894 CameraDevices           com.package.name                   I  Camera #0: Unavailable!
2023-10-24 17:36:48.949 22508-22585 CameraManagerGlobal     com.package.name                   I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.package.name API Level 1
2023-10-24 17:36:49.026 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 1: Capture Session #1001 configured!
2023-10-24 17:36:49.026 22508-23999 CameraManager           com.package.name                   I  Camera 1: Disconnected!
2023-10-24 17:36:49.028 22508-23999 CameraSession           com.package.name                   E  Camera Device android.hardware.camera2.impl.CameraDeviceImpl@51d64d2 has been disconnected!
                                                                                                    com.mrousavy.camera.core.CameraDisconnectedError: [session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: DISCONNECTED
                                                                                                    	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onDisconnected(CameraManager+openCamera.kt:38)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:246)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:237)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-10-24 17:36:49.028 22508-23999 CameraView              com.package.name                   E  invokeOnError(...):
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  com.mrousavy.camera.core.CameraDisconnectedError: [session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: DISCONNECTED
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onDisconnected(CameraManager+openCamera.kt:38)
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:246)
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  	at android.os.Handler.handleCallback(Handler.java:883)
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  	at android.os.Handler.dispatchMessage(Handler.java:100)
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  	at android.os.Looper.loop(Looper.java:237)
2023-10-24 17:36:49.029 22508-23999 System.err              com.package.name                   W  	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-10-24 17:36:49.037 22508-23999 CameraManager           com.package.name                   I  Camera 0: Opened!
2023-10-24 17:36:49.037 22508-23999 CameraSession           com.package.name                   I  Successfully configured Session with 1 outputs for Camera #1!
2023-10-24 17:36:49.037 22508-23999 CameraSession           com.package.name                   I  Updating Video Outputs...
2023-10-24 17:36:49.037 22508-23999 VideoPipeline           com.package.name                   I  Removing FrameProcessor Output...
2023-10-24 17:36:49.038 22508-23999 VideoPipeline           com.package.name                   I  Removing RecordingSession Output...
2023-10-24 17:36:49.038 22508-23999 CameraSession           com.package.name                   W  Preview Output is null, aborting...
2023-10-24 17:36:49.038 22508-23999 CameraSession           com.package.name                   I  Successfully updated CameraSession Configuration! isActive: true
2023-10-24 17:36:49.038 22508-23999 CameraView              com.package.name                   I  invokeOnInitialized()
2023-10-24 17:36:49.039 22508-22893 ReactNativeJS           com.package.name                   W  'Camera onError: ', { [session/camera-has-been-disconnected: [session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: DISCONNECTED]
                                                                                                      name: 'session/camera-has-been-disconnected',
                                                                                                      _code: 'session/camera-has-been-disconnected',
                                                                                                      _message: '[session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: DISCONNECTED',
                                                                                                      _cause: undefined }
2023-10-24 17:36:49.052 22508-23999 PreviewView             com.package.name                   I  Resizing PreviewView to 1024 x 768...
2023-10-24 17:36:49.052 22508-23999 CameraSession           com.package.name                   I  Successfully configured Camera #0!
2023-10-24 17:36:49.061 22508-23999 CameraSession           com.package.name                   I  Configuring Session for Camera #0...
2023-10-24 17:36:49.061 22508-23999 SurfaceOutput           com.package.name                   I  Closing 1472x1104 Video Pipeline..
2023-10-24 17:36:49.063 22508-23999 CameraSession           com.package.name                   I  Adding 1472 x 1104 Video Output in Format #34...
2023-10-24 17:36:49.063 22508-23999 VideoPipeline           com.package.name                   I  Initializing 1472 x 1104 Video Pipeline (format: NATIVE)
2023-10-24 17:36:49.073 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 0: Creating Capture Session #1002... Hardware Level: 2} | Outputs: [android.hardware.camera2.params.OutputConfiguration@d4d42a2b]
2023-10-24 17:36:49.074 22508-23999 CreateCaptureSession    com.package.name                   I  Using new API (>=28)
2023-10-24 17:36:49.075 22508-23999 CameraDeviceState       com.package.name                   I  Legacy camera service transitioning to state CONFIGURING
2023-10-24 17:36:49.076 22508-24114 RequestThread-0         com.package.name                   I  Configure outputs: 1 surfaces configured.
2023-10-24 17:36:49.076 22508-24114 Camera                  com.package.name                   D  app passed NULL surface
2023-10-24 17:36:49.089 22508-24115 libc                    com.package.name                   E  Access denied finding property "persist.camera.legacy_perf"
2023-10-24 17:36:49.095 22508-23999 CameraDeviceState       com.package.name                   I  Legacy camera service transitioning to state IDLE
2023-10-24 17:36:49.096 22508-23999 CameraSession           com.package.name                   I  Updating CameraSession Configuration...
2023-10-24 17:36:49.097 22508-23999 CameraSession           com.package.name                   W  Called configure(...) but nothing changed...
2023-10-24 17:36:49.097 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 1: Capture Session #1001 closed!
2023-10-24 17:36:49.097 22508-23999 CameraSession           com.package.name                   I  Camera Session android.hardware.camera2.impl.CameraCaptureSessionImpl@b48fc1e has been closed!
2023-10-24 17:36:49.098 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 0: Capture Session #1002 configured!
2023-10-24 17:36:49.098 22508-23999 CameraSession           com.package.name                   I  Updating CameraSession Configuration...
2023-10-24 17:36:49.107 22508-23999 CameraSession           com.package.name                   I  Configuring Session for Camera #1...
2023-10-24 17:36:49.107 22508-23999 SurfaceOutput           com.package.name                   I  Closing 1472x1104 Video Pipeline..
2023-10-24 17:36:49.110 22508-23999 CameraSession           com.package.name                   I  Adding 1472 x 1104 Video Output in Format #34...
2023-10-24 17:36:49.110 22508-23999 VideoPipeline           com.package.name                   I  Initializing 1472 x 1104 Video Pipeline (format: NATIVE)
2023-10-24 17:36:49.113 22508-23999 CameraSession           com.package.name                   I  Adding 1024 x 768 Preview Output...
2023-10-24 17:36:49.114 22508-23999 PreviewView             com.package.name                   I  Resizing PreviewView to 1024 x 768...
2023-10-24 17:36:49.124 22508-23999 CreateCaptureSession    com.package.name                   I  Camera 1: Creating Capture Session #1003... Hardware Level: 2} | Outputs: [android.hardware.camera2.params.OutputConfiguration@9b1a661a, android.hardware.camera2.params.OutputConfiguration@157a519]
2023-10-24 17:36:49.124 22508-23999 CreateCaptureSession    com.package.name                   I  Using new API (>=28)
2023-10-24 17:36:49.125 22508-23999 CameraSession           com.package.name                   E  Failed to configure CameraSession! Error: CameraDevice was already closed, Config-Diff: Difference(deviceChanged=false, outputsChanged=true, sidePropsChanged=true)
                                                                                                    java.lang.IllegalStateException: CameraDevice was already closed
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2550)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:648)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:634)
                                                                                                    	at com.mrousavy.camera.extensions.CameraDevice_createCaptureSessionKt.createCaptureSession(CameraDevice+createCaptureSession.kt:57)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.configureOutputs(CameraSession.kt:356)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.configure(CameraSession.kt:136)
                                                                                                    	at com.mrousavy.camera.core.CameraSession$configure$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:237)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-10-24 17:36:49.125 22508-23999 CameraView              com.package.name                   E  invokeOnError(...):
2023-10-24 17:36:49.125 22508-23999 System.err              com.package.name                   W  java.lang.IllegalStateException: CameraDevice was already closed
2023-10-24 17:36:49.125 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2550)
2023-10-24 17:36:49.125 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:648)
2023-10-24 17:36:49.125 22508-23999 System.err              com.package.name                   W  	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:634)
2023-10-24 17:36:49.125 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.extensions.CameraDevice_createCaptureSessionKt.createCaptureSession(CameraDevice+createCaptureSession.kt:57)
2023-10-24 17:36:49.125 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.core.CameraSession.configureOutputs(CameraSession.kt:356)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.core.CameraSession.configure(CameraSession.kt:136)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at com.mrousavy.camera.core.CameraSession$configure$1.invokeSuspend(Unknown Source:15)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at android.os.Handler.handleCallback(Handler.java:883)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at android.os.Handler.dispatchMessage(Handler.java:100)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at android.os.Looper.loop(Looper.java:237)
2023-10-24 17:36:49.126 22508-23999 System.err              com.package.name                   W  	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Camera Device

```json
{
  "hardwareLevel": "legacy",
  "neutralZoom": 1,
  "supportsFocus": true,
  "supportsLowLightBoost": false,
  "hasTorch": false,
  "supportsRawCapture": false,
  "sensorOrientation": "landscape-left",
  "maxZoom": 4,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "isMultiCam": false,
  "id": "1",
  "position": "front",
  "minZoom": 1,
  "hasFlash": false,
  "name": "FRONT (1)"
}
```

### Device

samsung tab A8

### VisionCamera Version

3.6.3

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by angelos3lex** [comment]
Resolved by removing key from the camera component:
 ```
 <Camera
    key={device.id} // <-- Remove this
```

I don't know how this affects the thing to be honest

**Comment by angelos3lex** [comment]
Oh that was happening because i was switching from back to front device very quickly. in `componentDidMount` i was changing the `CameraPosition` to `front` from `back` and this leads to the above error when also setting the `key` prop to camera component.
