### ISSUE TITLE
🐛 Galaxy S23 Ultra Unable to open camera

### ISSUE THREAD

**Issue by OPEN-9** [cuvent/react-native-vision-camera#2092]
### What's happening?

Galaxy S23 Ultra Unable to open camera，Is it because Samsung devices don't “wide-angle-camera”

### Reproduceable Code

```tsx
const [cameraDevices, setCameraDevices] = useState<
    PhysicalCameraDeviceType | LogicalCameraDeviceType | undefined
  >("wide-angle-camera")

const devices = useCameraDevices(cameraDevices)

<VisionCamera
            ref={camera}
            style={StyleSheet.absoluteFill}
            device={devices.back}
            isActive={isActive}
            enableZoomGesture={false}
            photo={true}
            video={false}
            audio={false}
            orientation="portrait"
            onError={onError}
            // frameProcessorFps={3}
            // frameProcessor={frameProcessor}
          />
```

### Relevant log output

```shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures(DrawableContainer.java:879)
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.getOpacity(DrawableContainer.java:1162)
       at android.graphics.drawable.DrawableContainer.getOpacity(DrawableContainer.java:433)
       at android.graphics.drawable.InsetDrawable.getOpacity(InsetDrawable.java:260)
       at android.view.View.computeOpaqueFlags(View.java:20566)
       at android.view.View.setBackgroundDrawable(View.java:25946)
       at androidx.appcompat.widget.AppCompatEditText.setBackgroundDrawable(AppCompatEditText.java:109)
       at android.view.View.setBackground(View.java:25839)
       at android.view.View.<init>(View.java:6410)
       at android.widget.TextView.<init>(TextView.java:1291)
       at android.widget.EditText.<init>(EditText.java:99)
       at android.widget.EditText.<init>(EditText.java:95)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:73)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
       at com.facebook.react.views.textinput.ReactEditText.<init>(ReactEditText.java:124)
       at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:123)
       at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:79)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:847)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Camera Device

```json
1
```

### Device

Galaxy S23 Ultra

### VisionCamera Version

"react-native-vision-camera": "2.13.0"

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Please upgrade to the latest version (V3).
