### ISSUE TITLE
🐛 startRecording() function not working.

### ISSUE THREAD

**Issue by randomstuff222** [cuvent/react-native-vision-camera#2139]
### What's happening?

I have my code set up so when I click a button, it will start the recording function, and once I click the stop button, it stops the recording and saves the path. But whenever I start the recording, I run into an "unknown/capture" error.
This error is also on the example react native vision camera
![image](https://github.com/mrousavy/react-native-vision-camera/assets/30642220/862653ab-abf7-41ee-a879-079580b874b0)

### Reproduceable Code

```tsx
const startRecording = async () => {
    try{
      setRecordingStatus(true);
      await cameraRef.current?.startRecording({
        flash: 'off',
        onRecordingFinished: video => {
          setVideoPath(video.path);
          setRecordedVideo(video);
        },
        onRecordingError(error) {
          console.log('Recording Error: ', error);
        },
      })
    }catch (e){
      console.log('Error while trying to start recording: ', e);
    }

  };
  const stopRecording = async () => {
    setRecordingStatus(false);
    await cameraRef.current?.stopRecording();
  };
return(
<View style={[styles.container, { flexDirection: 'column' }]}>
      <View style={{ flex: 5 }}>
        <Camera 
          ref={cameraRef}
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          video={true}
        />
</View>
<TouchableOpacity
              style={styles.startingRecordingButton}
              onPress={stopRecording}
            />
            <TouchableOpacity
              style={styles.waitingRecordButton}
              onPress={startRecording}
            />
</View>
)
```

### Relevant log output

```shell
Opening the app on Android...
info JS server already running.
info Installing the app...
> Task :gradle-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:classes UP-TO-DATE
> Task :gradle-plugin:jar UP-TO-DATE
> Task :gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE

> Configure project :react-native-vision-camera
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!

> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :react-native-video:preBuild UP-TO-DATE
> Task :react-native-video:preDebugBuild UP-TO-DATE
> Task :react-native-video:compileDebugAidl NO-SOURCE
> Task :react-native-vision-camera:preBuild UP-TO-DATE
> Task :react-native-vision-camera:preDebugBuild UP-TO-DATE
> Task :react-native-vision-camera:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-video:packageDebugRenderscript NO-SOURCE
> Task :react-native-vision-camera:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :react-native-video:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-vision-camera:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :react-native-video:compileDebugRenderscript NO-SOURCE
> Task :react-native-video:generateDebugResValues UP-TO-DATE
> Task :react-native-video:generateDebugResources UP-TO-DATE
> Task :react-native-video:packageDebugResources UP-TO-DATE
> Task :react-native-vision-camera:compileDebugRenderscript NO-SOURCE
> Task :react-native-vision-camera:generateDebugResValues UP-TO-DATE
> Task :react-native-vision-camera:generateDebugResources UP-TO-DATE
> Task :react-native-vision-camera:packageDebugResources UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-video:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-video:processDebugManifest UP-TO-DATE
> Task :react-native-vision-camera:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-vision-camera:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :react-native-video:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-video:parseDebugLocalResources UP-TO-DATE
> Task :react-native-video:generateDebugRFile UP-TO-DATE
> Task :react-native-vision-camera:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-vision-camera:parseDebugLocalResources UP-TO-DATE
> Task :react-native-vision-camera:generateDebugRFile UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :react-native-video:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-video:javaPreCompileDebug UP-TO-DATE
> Task :react-native-video:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-video:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-vision-camera:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-vision-camera:compileDebugKotlin UP-TO-DATE
> Task :react-native-vision-camera:javaPreCompileDebug UP-TO-DATE
> Task :react-native-vision-camera:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-vision-camera:bundleLibCompileToJarDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :react-native-video:mergeDebugShaders UP-TO-DATE
> Task :react-native-video:compileDebugShaders NO-SOURCE
> Task :react-native-video:generateDebugAssets UP-TO-DATE
> Task :react-native-video:packageDebugAssets UP-TO-DATE
> Task :react-native-vision-camera:mergeDebugShaders UP-TO-DATE
> Task :react-native-vision-camera:compileDebugShaders NO-SOURCE
> Task :react-native-vision-camera:generateDebugAssets UP-TO-DATE
> Task :react-native-vision-camera:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :react-native-video:processDebugJavaRes NO-SOURCE
> Task :react-native-video:bundleLibResDebug NO-SOURCE
> Task :react-native-vision-camera:processDebugJavaRes NO-SOURCE
> Task :react-native-vision-camera:bundleLibResDebug UP-TO-DATE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :react-native-video:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-vision-camera:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeProjectDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-video:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-video:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-video:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-vision-camera:configureCMakeDebug[arm64-v8a]
> Task :react-native-vision-camera:buildCMakeDebug[arm64-v8a]
> Task :react-native-vision-camera:configureCMakeDebug[armeabi-v7a]
> Task :react-native-vision-camera:buildCMakeDebug[armeabi-v7a]
> Task :react-native-vision-camera:configureCMakeDebug[x86]
> Task :react-native-vision-camera:buildCMakeDebug[x86]
> Task :react-native-vision-camera:configureCMakeDebug[x86_64]
> Task :react-native-vision-camera:buildCMakeDebug[x86_64]
> Task :react-native-vision-camera:externalNativeBuildDebug
> Task :react-native-vision-camera:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-vision-camera:mergeDebugNativeLibs UP-TO-DATE
> Task :react-native-vision-camera:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:createDebugApkListingFileRedirect UP-TO-DATE

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Device' for :app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 37s
```
When trying to start recording
```shell
 Recording Error:  {"cause": {"message": "prepare failed:-22", "stacktrace": "java.io.IOException: prepare failed:-22       
        at android.media.MediaRecorder._prepare(Native Method)
        at android.media.MediaRecorder.prepare(MediaRecorder.java:1635)
        at com.mrousavy.camera.core.RecordingSession.start(RecordingSession.kt:91)
        at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:517)
        at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:56)
        at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying to start a video recording! prepare failed:-22", "userInfo": null}
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 0.6000000238418579,
  "supportsLowLightBoost": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "ultra-wide-angle-camera",
    "wide-angle-camera",
    "telephoto-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": true,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Galaxy A52 (Android)

### VisionCamera Version

3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

Yes, is reproduced on the example

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hm, "prepare failed -22" - I've seen that before

**Comment by mrousavy** [comment]
Can you try to use a low-resolution `format`?

E.g. something like:

```ts
const format = useCameraFormat(device, [
  { videoResolution: { width: 640, height: 480 } }
])
```

Does that work for you?

**Comment by mrousavy** [comment]
Can you play around with the bitrate settings? Maybe the bitrate is wrong?

**Comment by randomstuff222** [comment]
I tried playing around with both (changing the video bitrate, and the format settings) settings, but I still get the same error.

**Comment by mrousavy** [comment]
Can you maybe tell me what exactly you did instead of just saying you changed something? Which formats did you try?

**Comment by randomstuff222** [comment]
I did this:
```js
const format = useCameraFormat(device, [
    { videoResolution: { width: 640, height: 480 }}
  ])
```
With the format, and also added the bitrate on the recorindg
```js
await cameraRef.current?.startRecording({
        flash: 'off',
        videoBitRate: 'low',
```
However, I was able to solve the issue by adding this to the format
```js
const format = useCameraFormat(device, [
    { videoResolution: { width: 640, height: 480 }, pixelFormat: 'native' }
  ])
```

So now is working

**Comment by mrousavy** [comment]
Aha - so the `pixelFormat` 'yuv' was not properly working? weird...

**Comment by Alejandro192** [comment]
> Can you try to use a low-resolution `format`?
> 
> E.g. something like:
> 
> ```ts
> const format = useCameraFormat(device, [
>   { videoResolution: { width: 640, height: 480 } }
> ])
> ```
> 
> Does that work for you?

This works for me

**Comment by itzyashh** [comment]
`const screen = Dimensions.get('screen')`

`const format = useCameraFormat(device, [
  {
    videoAspectRatio: screen.height / screen.width,
  }
  ])`

This worked for me , I'm using samsung A42

**Comment by itzyashh** [comment]
> > Can you try to use a low-resolution `format`?
> > E.g. something like:
> > ```ts
> > const format = useCameraFormat(device, [
> >   { videoResolution: { width: 640, height: 480 } }
> > ])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does that work for you?
> 
> This works for me

This video resolution was working for me 

But I don't want to compromise on quality so I used different soln
`const screen = Dimensions.get('screen')`

`const format = useCameraFormat(device, [
  {
    videoAspectRatio: screen.height / screen.width,
  }
  ])`

This worked for me , I'm using samsung A42
