### ISSUE TITLE
🐛  Camera is not mounting, onInitialized callback is not being called

### ISSUE THREAD

**Issue by Relie9828** [cuvent/react-native-vision-camera#2143]
### What's happening?

I'm trying to use the react-native-vision-camera library in my application, but the camera is not mounting because the onInitialized callback is not being called. I'm not exactly sure why this is happening as I've followed the documentation closely.

### Dev Deps
- Expo workflow: bare
- "expo": "~49.0.15",
- "react-native": "0.72.6",
- "react-native-vision-camera": "^3.6.4",
- "react-native-reanimated": "~3.3.0",
- "react-native-worklets-core": "^0.2.4",

### Reproduceable Code

```tsx
import { Camera, useCameraDevices, useCameraPermission } from 'react-native-vision-camera';
import { View, StyleSheet, TouchableOpacity, Text, Image, } from 'react-native';
import React, { useEffect, useState, useRef } from 'react';

function App() {
    
    const { hasPermission, requestPermission } = useCameraPermission();

    const camera = useRef(null);
    const devices = useCameraDevices('back');

    const [isCameraReady, setIsCameraReady] = useState(false);
    const [showCamera, setShowCamera] = useState(false);
    const [permissionAuth, setPermissionsAuth] = useState('')
    const [imageSource, setImageSource] = useState('');

    useEffect(() => {
        requestPermission();
        const checkPermission = async () => {
            const status = await Camera.getCameraPermissionStatus();
            setPermissionsAuth(status)
            if (status !== 'granted') {
                return null
            } else if (status === 'granted') {
                setShowCamera(true)
            }
        };

        checkPermission();
    }, []);

    // Checking if the permission are true
    // To redirect to settings if camera is false but the status is granted
    console.log(hasPermission, permissionAuth);

    const capturePhoto = async () => {
        console.log(isCameraReady)
        if (camera.current !== null && isCameraReady) {
            const photo = await camera.current.takePhoto({});
            setImageSource(photo.path);
            setShowCamera(false);
            console.log(photo.path);
        }
    };

    if (devices == null) {
        return <Text style={{ color: 'white', }}>Camera not available</Text>;
    };

    return (
        <View style={styles.container}>
            {showCamera ? (
                <>
                <Camera
                    ref={camera}
                    style={[StyleSheet.absoluteFill, {backgroundColor: 'black',}]}
                    device={devices}
                    isActive={showCamera}
                    resizeMode='cover'
                    onInitialized={() => setIsCameraReady(true)}
                    photo
                />

                    <View style={styles.buttonContainer}>
                        <TouchableOpacity
                            style={styles.camButton}
                            onPress={() => capturePhoto()}
                        />
                    </View>
                </>
            ) : (
                <>
                    {imageSource !== '' ? (
                        <Image
                            style={styles.image}
                            source={{
                                uri: `file://'${imageSource}`,
                            }}
                        />
                    ) : null}

                    <View style={styles.backButton}>
                        <TouchableOpacity
                            style={{
                                backgroundColor: 'rgba(0,0,0,0.2)',
                                padding: 10,
                                justifyContent: 'center',
                                alignItems: 'center',
                                borderRadius: 10,
                                borderWidth: 2,
                                borderColor: '#fff',
                                width: 100,
                            }}
                            onPress={() => setShowCamera(true)}>
                            <Text style={{ color: 'white', fontWeight: '500' }}>Back</Text>
                        </TouchableOpacity>
                    </View>
                    <View style={styles.buttonContainer}>
                        <View style={styles.buttons}>
                            <TouchableOpacity
                                style={{
                                    backgroundColor: '#fff',
                                    padding: 10,
                                    justifyContent: 'center',
                                    alignItems: 'center',
                                    borderRadius: 10,
                                    borderWidth: 2,
                                    borderColor: '#77c3ec',
                                }}
                                onPress={() => setShowCamera(true)}>
                                <Text style={{ color: '#77c3ec', fontWeight: '500' }}>
                                    Retake
                                </Text>
                            </TouchableOpacity>
                            <TouchableOpacity
                                style={{
                                    backgroundColor: '#77c3ec',
                                    padding: 10,
                                    justifyContent: 'center',
                                    alignItems: 'center',
                                    borderRadius: 10,
                                    borderWidth: 2,
                                    borderColor: 'white',
                                }}
                                onPress={() => setShowCamera(true)}>
                                <Text style={{ color: 'white', fontWeight: '500' }}>
                                    Use Photo
                                </Text>
                            </TouchableOpacity>
                        </View>
                    </View>
                </>
            )}
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    button: {
        backgroundColor: 'gray',
    },
    backButton: {
        backgroundColor: 'rgba(0,0,0,0.0)',
        position: 'absolute',
        justifyContent: 'center',
        width: '100%',
        top: 0,
        padding: 20,
    },
    buttonContainer: {
        backgroundColor: 'rgba(0,0,0,0.2)',
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        bottom: 0,
        padding: 20,
    },
    buttons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    camButton: {
        height: 80,
        width: 80,
        borderRadius: 40,
        //ADD backgroundColor COLOR GREY
        backgroundColor: '#B2BEB5',

        alignSelf: 'center',
        borderWidth: 4,
        borderColor: 'white',
    },
    image: {
        width: '100%',
        height: '100%',
        aspectRatio: 9 / 16,
    },
});

export default App;
```

### Relevant log output

```shell
Possible Unhandled Promise Rejection (id: 0):
session/camera-not-ready: The Camera is not ready yet! Wait for the onInitialized() callback!
[session/camera-not-ready]: The Camera is not ready yet! Wait for the onInitialized() callback!
    at construct (native)
    at apply (native)
    at _construct (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4485:28)
    at Wrapper (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4443:25)
    at construct (native)
    at _createSuperInternal (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:161392:322)
    at call (native)
    at CameraError (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:161409:26)
    at construct (native)
    at _createSuperInternal (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:161392:322)
    at apply (native)
    at CameraRuntimeError (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:161466:27)
    at tryParseNativeCameraError (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:161505:38)
    at ?anon_0_ (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:160947:62)
    at throw (native)
    at asyncGeneratorStep (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6087:26)
    at _throw (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6109:29)
    at tryCallOne (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39710:26)
    at _callTimer (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39589:17)
    at _callReactNativeMicrotasksPass (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39634:17)
    at callReactNativeMicrotasks (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39840:44)
    at __callReactNativeMicrotasks (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3643:46)
    at anonymous (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3417:45)
    at __guard (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3616:15)
    at flushedQueue (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3416:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.xxx:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3410:33)
```

### Camera Device

```json
{
  "supportsLowLightBoost": false
  "format": [{...}],
  "hardwareLevel": "full",
  "supportsFocus": true,
  "supportsRawCapture": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera",
    "telephoto-camera"
  ],
  "position": "back",
  "maxZoom": 123.75,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:3",
  "isMultiCam": true,
  "hasTorch": true,
  "hasFlash": true,
  "name": "Back Dual Camera",
  "minZoom": 1,
  "sensorOrientation": "landscape-right"
}
```

### Device

- iPhone 14 pro (17.0.0)
- iPhone 15 pro (17.0.0)
- Galaxy s22 (Android 13) 
- Galaxy a72 (Android 13)

### VisionCamera Version

3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [x] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by bglgwyng** [comment]
I've experienced a similar thing. Did you turn off/on your app and see the camera work well again? In my case, just turning off/on the app didn't work. I had to turn off/on my phone.

**Comment by Relie9828** [comment]
> I've experienced a similar thing. Did you turn off/on your app and see the camera work well again? In my case, just turning off/on the app didn't work. I had to turn off/on my phone.

Yeah I tried that as well, but unfortunately both attempts did not work.

**Comment by Relie9828** [comment]
I found others with similar issues #1363, #1560, #855, #1191, [stackOverflow](https://stackoverflow.com/questions/72946403/react-native-vision-camera-doesnt-appears-after-initialization)

**Comment by Relie9828** [comment]
#1363

**Comment by mrousavy** [comment]
Huh? You're saying you use VisionCamera 3.6.x but you use the `useCameraDevices` hook? In V3 you need `useCameraDevice`.

**Comment by Relie9828** [comment]
> Huh? You're saying you use VisionCamera 3.6.x but you use the `useCameraDevices` hook? In V3 you need `useCameraDevice`.

I corrected the typo bu the CameraView is still not mounted.

**Comment by flaviodamaiajr** [comment]
I have the same issue. Any idea how to solve it?

**Comment by mrousavy** [comment]
Can you please share a video recording of what's happening? I cannot reproduce this on an iPhone 15 Pro (17.0.0) with the versions you sent.

![Screenshot 2023-11-15 at 20 18 32](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/e4fc79a3-5bfc-44ba-a62f-d159c1c3928a)

**Comment by Relie9828** [comment]
> Can you please share a video recording of what's happening? I cannot reproduce this on an iPhone 15 Pro (17.0.0) with the versions you sent.
> 
> ![Screenshot 2023-11-15 at 20 18 32](https://user-images.githubusercontent.com/15199031/283224344-e4fc79a3-5bfc-44ba-a62f-d159c1c3928a.png)

Unfortunate not since, the 15 pro I'm using is on emulator but the behavior is the same as the physical 14 pro on my end.

**Comment by mrousavy** [comment]
Then please do the screen recording on the iPhone 14.

**Comment by mrousavy** [comment]
Ah no sorry - I meant of the Example app. You said you could reproduce it here in the Example app

**Comment by Relie28** [comment]
> Ah no sorry - I meant of the Example app. You said you could reproduce it here in the Example app

Yeah that's from the example app I provided at the top. Sorry using my work account. Also was the example code that I provided functional on your end?

**Comment by gaabrielricci** [comment]
I have the same issue here, with IOS 17. in my case is on iphone 14. The camera is not initializing,

**Comment by rodgomesc** [comment]
@Relie28 when he says "example app", he's talking specifically about the example app provided in this repository with the camera lib, in `package/example`

**Comment by mrousavy** [comment]
Hey! Thanks for reporting this issue.

I've been working the past days on making sure the Camera lifecycle is safely handled and released when needed to make sure this crash doesn't occur anymore.

I just created a PR for this - can you please this to see if that fixes the issue for you? https://github.com/mrousavy/react-native-vision-camera/pull/2339

If this fixes your issue, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support me / thank me for building VisionCamera and continuously improving it. 

If this does not fix your issue, please clone the repo, check out the branch `fix/blackscreen` (the PR above), run the Example app, reproduce your issue there and share the `adb logcat` logs with me (upload to pastebin or gist) so I can investigate this further.

Thank you! 🙏
