### ISSUE TITLE
Android crash when permission change at background 🐛 

### ISSUE THREAD

**Issue by BrianCodeItUp** [cuvent/react-native-vision-camera#2188]
### What's happening?

I have a screen with code scanner feature. I will ask permission will user enter the screen. After user granted the camera permission. `Camera` component will render. If user go to setting and change camera permission, the app will crash when the app comes back to foreground.

### Reproduceable Code

```tsx
const [isPermissionGranted, setIsPermissionGranted] = useState(false);
useEffect(() => {
  async function handlePermission () {
    const result = await checkPermission();
      if (!result) {
        navigation.goBack();
        return;
      }
   setIsEnablePermission(!!result);
  }
  handlePermission()
 }, []);

const codeScanner = useCodeScanner({
    codeTypes: ['qr'],
    onCodeScanned: handleScanByCamera,
 });
const device = useCameraDevice('back');

return (
  <Camera
    style={StyleSheet.absoluteFill}
    device={device}
    isActive={isFocus && appState === 'active'}
    photo={true}
    codeScanner={codeScanner}
    torch={flashStatus ? 'on' : 'off'}
 />
)
```

### Relevant log output

```shell
2023-11-20 18:24:48.401 24219-25144 CameraManager           app.zqb.android.dev                  E  Camera 0: Error! 3
2023-11-20 18:24:48.404 24219-25144 CameraSession           app.zqb.android.dev                  E  Camera Device android.hardware.camera2.impl.CameraDeviceImpl@3d02098 has been disconnected!
                                                                                                    com.mrousavy.camera.core.CameraDisconnectedError: [session/camera-has-been-disconnected] The given Camera device (id: 0) has been disconnected! Error: CAMERA_IS_DISABLED_BY_ANDROID
                                                                                                    	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onError(CameraManager+openCamera.kt:49)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:2013)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
                                                                                                    	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
                                                                                                    	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
                                                                                                    	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
                                                                                                    	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-11-20 18:24:48.404 24219-25144 CameraView              app.zqb.android.dev                  E  invokeOnError(...):
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  com.mrousavy.camera.core.CameraDisconnectedError: [session/camera-has-been-disconnected] The given Camera device (id: 0) has been disconnected! Error: CAMERA_IS_DISABLED_BY_ANDROID
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onError(CameraManager+openCamera.kt:49)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:2013)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.os.Handler.handleCallback(Handler.java:883)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.os.Handler.dispatchMessage(Handler.java:100)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.os.Looper.loop(Looper.java:224)
2023-11-20 18:24:48.405 24219-25144 System.err              app.zqb.android.dev                  W  	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-11-20 18:24:48.632  1304-1423  InputDispatcher         system_server                        E  channel '17a1751 app.zqb.android.dev/com.wellpay.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
---------------------------- PROCESS ENDED (24219) for package app.zqb.android.dev ----------------------------
2023-11-20 18:24:54.530  1731-1731  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: taskId=718   userId=0   baseIntent=Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:app.zqb.android.dev flg=0x10100000 cmp=com.android.settings/.applications.InstalledAppDetails }
2023-11-20 18:24:54.530  1731-1731  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: taskId=722   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=app.zqb.android.dev/com.wellpay.MainActivity }
2023-11-20 18:24:54.569  1731-1731  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: taskId=718   userId=0   baseIntent=Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:app.zqb.android.dev flg=0x10100000 cmp=com.android.settings/.applications.InstalledAppDetails }
2023-11-20 18:24:54.569  1731-1731  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: taskId=722   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=app.zqb.android.dev/com.wellpay.MainActivity }
2023-11-20 18:24:54.613  1731-1731  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: taskId=718   userId=0   baseIntent=Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:app.zqb.android.dev flg=0x10100000 cmp=com.android.settings/.applications.InstalledAppDetails }
2023-11-20 18:24:54.613  1731-1731  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: taskId=722   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=app.zqb.android.dev/com.wellpay.MainActivity }
2023-11-20 18:24:55.615 18745-18864 SuggestManager          com.miui.securitycenter.remote       E  openApp name = app.zqb.android.dev
--------- beginning of crash
2023-11-20 18:24:55.855 25447-25447 AndroidRuntime          pid-25447                            E  FATAL EXCEPTION: main
                                                                                                    Process: app.zqb.android.dev, PID: 25447
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.zqb.android.dev/com.wellpay.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3338)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7561)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                                                                                                    Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
                                                                                                    	at com.wellpay.MainActivity.onCreate(MainActivity.java:42)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:224) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7561) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                                                                                                    	at com.wellpay.MainActivity.onCreate(MainActivity.java:42) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:224) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7561) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 
                                                                                                    Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
                                                                                                    	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:57)
                                                                                                    	at com.swmansion.rnscreens.ScreenStackFragment.<init>(ScreenStackFragment.kt:38)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613) 
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                                                                                                    	at com.wellpay.MainActivity.onCreate(MainActivity.java:42) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:224) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7561) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 
2023-11-20 18:24:55.885  1304-1423  InputDispatcher         system_server                        E  channel '3541f16 app.zqb.android.dev/com.wellpay.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
---------------------------- PROCESS STARTED (25474) for package app.zqb.android.dev ----------------------------
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Redmi

### VisionCamera Version

3.6.6

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by rodgomesc** [comment]
whoaa, that's interesting

**Comment by rodgomesc** [comment]
@mrousavy  i'm wondering if we  should pause the camera session and release resources when the app is on foreground

**Comment by mrousavy** [comment]
> CAMERA_IS_DISABLED_BY_ANDROID

interesting, well this should def. be an error (`Camera`'s `onError` prop), but it shouldn't crash the entire app

**Comment by blueworlds1** [comment]
Also seeing this error in our logs, but it didn't crash the app

**Comment by mrousavy** [comment]
Hey! Thanks for reporting this issue.

I've been working the past days on making sure the Camera lifecycle is safely handled and released when needed to make sure this crash doesn't occur anymore.

I just created a PR for this - can you please this to see if that fixes the issue for you? https://github.com/mrousavy/react-native-vision-camera/pull/2339

If this fixes your issue, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support me / thank me for building VisionCamera and continuously improving it. 

If this does not fix your issue, please clone the repo, check out the branch `fix/blackscreen` (the PR above), run the Example app, reproduce your issue there and share the `adb logcat` logs with me (upload to pastebin or gist) so I can investigate this further.

Thank you! 🙏
