### ISSUE TITLE
🐛 Error: TOO_MANY_OPEN_CAMERAS after reopening camera page

### ISSUE THREAD

**Issue by hanna-buhai** [cuvent/react-native-vision-camera#2240]
### What's happening?

Note: to reproduce the bug on example app, you need to create new initial screen instead of setting Camera as `initialRouteName`. The bug doesn't happen when you navigate to new screens that are being added on top of Camera screen in navigation stack

Steps to reproduce (default cameraPosition is `back`):
1) navigate to Camera Screen
2) switch to `front` cameraPosition
3) navigate back
4) reopen the Camera Screen

The camera screen is black and you get TOO_MANY_OPEN_CAMERAS error. This only happens when the Camera screen is unmounted while the selected cameraPosition doesn't match the default value. So, if the default cameraPosition='front', it happens when you unmount on active back camera.
If you flip the camera multiple times and close the screen while the default camera is active, there is no error.

### Reproduceable Code

```tsx
// here is the device, format and camera configuration

import { useIsFocused } from '@react-navigation/native';
import {
	Camera,
	useCameraDevice,
	getCameraFormat,
	Templates,
} from 'react-native-vision-camera';

export const CameraView = () => {
	const isFocused = useIsFocused();
	const [cameraPosition, setCameraPosition] = useState<'front' | 'back'>(
		'back'
	);

	const device = useCameraDevice(cameraPosition);
	const format = !!device
		? getCameraFormat(device, Templates.Snapchat)
		: undefined;
	const camera = useRef<Camera>(null);

	// ...

	return (
		<Camera
			ref={camera}
			style={StyleSheet.absoluteFill}
			device={device}
			format={format}
			video={true}
			isActive={isFocused}
			audio={true}
			enableZoomGesture={true}
		/>
	);
};
```

### Relevant log output

```shell
12-01 11:47:34.447 19796 19932 I CameraDevices: Camera #0: Unavailable!
12-01 11:47:34.447  1272  1283 D HwBatteryService: cameraUpdateLight enable false
12-01 11:47:34.447   658  1368 I HwCameraServiceEx: disconnect: Disconnected client for camera 0 for PID 19796
12-01 11:47:34.448 19796 19932 I CameraDevices: Camera #0: Available!
12-01 11:47:34.450   658  1368 I         : close camera, send msg to nfc, open nfc
12-01 11:47:34.450  1938  2110 D ScenarioService: camera end : com.app.name, last: com.app.name, pkgs: {com.app.name=27278868}
12-01 11:47:34.450  1938  2329 I PGServer: report state:10019 event type:1 pid:0 uid:0 pkg:com.app.name to pid: 1938
12-01 11:47:34.450   658  1368 I Camera2ClientBase: Closed Camera 0. Client was: com.app.name (PID 19796, UID 10469)
12-01 11:47:34.453 19796 20210 E CameraManager: Camera 0: Error! 2
12-01 11:47:34.457 19796 19796 I ViewRootImpl: jank_removeInvalidNode jank list is null
12-01 11:47:34.457 19796 20210 E CameraSession: Failed to configure CameraSession! Error: [session/camera-cannot-be-opened] The given Camera device (id: 0) could not be opened! Error: TOO_MANY_OPEN_CAMERAS, Config-Diff: Difference(deviceChanged=true, outputsChanged=true, sidePropsChanged=true)
12-01 11:47:34.457 19796 20210 E CameraSession: com.mrousavy.camera.core.CameraCannotBeOpenedError: [session/camera-cannot-be-opened] The given Camera device (id: 0) could not be opened! Error: TOO_MANY_OPEN_CAMERAS
12-01 11:47:34.457 19796 20210 E CameraSession: 	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onError(CameraManager+openCamera.kt:47)
12-01 11:47:34.457 19796 20210 E CameraSession: 	at android.hardware.camera2.impl.CameraDeviceImpl$8.run(CameraDeviceImpl.java:352)
12-01 11:47:34.457 19796 20210 E CameraSession: 	at android.os.Handler.handleCallback(Handler.java:907)
12-01 11:47:34.457 19796 20210 E CameraSession: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-01 11:47:34.457 19796 20210 E CameraSession: 	at android.os.Looper.loop(Looper.java:216)
12-01 11:47:34.457 19796 20210 E CameraSession: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-01 11:47:34.457 19796 20210 E CameraView: invokeOnError(...):
12-01 11:47:34.458 19796 20210 W System.err: com.mrousavy.camera.core.CameraCannotBeOpenedError: [session/camera-cannot-be-opened] The given Camera device (id: 0) could not be opened! Error: TOO_MANY_OPEN_CAMERAS
12-01 11:47:34.458 19796 20210 W System.err: 	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onError(CameraManager+openCamera.kt:47)
12-01 11:47:34.458 19796 20210 W System.err: 	at android.hardware.camera2.impl.CameraDeviceImpl$8.run(CameraDeviceImpl.java:352)
12-01 11:47:34.458 19796 20210 W System.err: 	at android.os.Handler.handleCallback(Handler.java:907)
12-01 11:47:34.458 19796 20210 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-01 11:47:34.458 19796 20210 W System.err: 	at android.os.Looper.loop(Looper.java:216)
12-01 11:47:34.458 19796 20210 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-01 11:47:34.478  1272  1366 V WindowManager: addAppToken: AppWindowToken{98371e token=Token{bcbef59 ActivityRecord{df4c7a0 u0 com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity t869}}} controller={TaskWindowContainerController taskId=869} at 2147483647
12-01 11:47:34.481   582   826 D         : doWinFrameOptStatusRecog begin to recog Layer result=2
12-01 11:47:34.484 19796 19931 E ReactNativeJS: 'Camera.onError(session/camera-cannot-be-opened): [session/camera-cannot-be-opened] The given Camera device (id: 0) could not be opened! Error: TOO_MANY_OPEN_CAMERAS', { [session/camera-cannot-be-opened: [session/camera-cannot-be-opened] The given Camera device (id: 0) could not be opened! Error: TOO_MANY_OPEN_CAMERAS]
12-01 11:47:34.484 19796 19931 E ReactNativeJS:   name: 'session/camera-cannot-be-opened',
12-01 11:47:34.484 19796 19931 E ReactNativeJS:   _code: 'session/camera-cannot-be-opened',
12-01 11:47:34.484 19796 19931 E ReactNativeJS:   _message: '[session/camera-cannot-be-opened] The given Camera device (id: 0) could not be opened! Error: TOO_MANY_OPEN_CAMERAS',
12-01 11:47:34.484 19796 19931 E ReactNativeJS:   _cause: undefined }
12-01 11:47:34.513 19796 19796 I CameraView: Updating CameraSession...
12-01 11:47:34.514 19796 20210 I CameraSession: Updating CameraSession Configuration...
12-01 11:47:34.515 19796 20210 I CameraSession: Configuring Camera #0...
12-01 11:47:34.515 19796 20210 I CameraManager: Camera 0: Opening...
12-01 11:47:34.528 19796 20210 I CameraManager: open camera: 0, package name: com.app.name
12-01 11:47:34.530  1664  4950 E HSM_SEC_BG: BMNCaller:is not PermissionEnabled.
12-01 11:47:34.531 19796 20210 I HwCameraUtil: notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
12-01 11:47:34.532   658  1368 I HwCameraServiceEx: CameraService::connectDevice E (pid 19796 "com.app.name", id 0)
12-01 11:47:34.532   658  1368 I HwCameraServiceEx: CameraService::connect call (PID -1 "com.app.name", camera ID 0) for HAL version default and Camera API version 2
12-01 11:47:34.533   658  1368 I HwCameraServiceEx: validateClientPermissionsLocked(), client user id: 10469
12-01 11:47:34.535   658  1368 I HwCameraServiceEx: updateEvictedList(), evicted size: 0, incomming package name: 'com.app.name'.
12-01 11:47:34.535   658  1239 I Camera3-Device: disconnect: E
12-01 11:47:34.535   658  1239 I Camera3-Device: disconnect: X, device has been disconnected before.
12-01 11:47:34.535   658  1368 I Camera2ClientBase: Camera 0: Opened. Client: com.app.name (PID 19796, UID 10469)
12-01 11:47:34.535   658  1368 I HwPerformEx: HwPerformEx(0xf2005480), camera 0.
12-01 11:47:34.535   658  1368 I CameraDeviceClient: CameraDeviceClient 0: Opened
12-01 11:47:34.535   658  1368 I HwCameraServiceEx: connectHelper(), make client for 'com.app.name'.
12-01 11:47:34.538   658  1368 I HwCameraServiceEx: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0
12-01 11:47:34.539   658  1368 E Camera3-Device: Camera 0: initialize: Could not open camera session: Too many users (-87)
12-01 11:47:34.539   658  1368 E Camera2ClientBase: initializeImpl: Camera 0: unable to initialize device: Too many users (-87)
12-01 11:47:34.539   658  1368 E HwCameraServiceEx: connectHelper: Could not initialize client from HAL.
12-01 11:47:34.539   658  1368 I CameraDeviceClient: ~CameraDeviceClient 0: Released!
12-01 11:47:34.539   658  1368 I HwPerformEx: ~HwPerformEx(0xf2005480), camera 0.
12-01 11:47:34.539   658  1368 I Camera3-Device: disconnect: E
12-01 11:47:34.539   658  1368 I Camera3-Device: disconnect: X, device has been disconnected before.
12-01 11:47:34.539   658  1368 I Camera3-Device: disconnect: E
12-01 11:47:34.539   658  1368 I Camera3-Device: disconnect: X, device has been disconnected before.
12-01 11:47:34.539 19796 19932 I CameraDevices: Camera #0: Unavailable!
12-01 11:47:34.540  1559  1828 D FlashlightController: dispatchAvailabilityChanged(false)
12-01 11:47:34.540  1272  1366 D HwBatteryService: cameraUpdateLight enable false
12-01 11:47:34.541  1559  1559 I ColorPickUitls: type = 2
12-01 11:47:34.542  1272  1413 D HiDATA_HiStream: onCameraUnavailable cameraId = 0
12-01 11:47:34.543   658  1368 I HwCameraServiceEx: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=1
12-01 11:47:34.544  1272  1413 D HiDATA_HiStream: onCameraAvailable cameraId = 0
12-01 11:47:34.544  1272  1366 D HwBatteryService: cameraUpdateLight enable false
12-01 11:47:34.544   658  1368 I HwCameraServiceEx: disconnect: Disconnected client for camera 0 for PID 19796
12-01 11:47:34.545  1938  2110 I DeviceStateService: torch mode changed: false, id: 0
12-01 11:47:34.545   661   764 E dubaid  : [CameraHandler.cpp] handleOnDisconnected# Invalid tag: 4
12-01 11:47:34.545  1938  2110 D ScenarioService: camera end : com.app.name, last: com.app.name, pkgs: {}
12-01 11:47:34.546  1938  2329 I PGServer: report state:10019 event type:1 pid:0 uid:0 pkg:com.app.name to pid: 1938
12-01 11:47:34.546   658  1368 I         : close camera, send msg to nfc, open nfc
12-01 11:47:34.546  1559  1828 D FlashlightController: dispatchAvailabilityChanged(true)
12-01 11:47:34.547   658  1368 I Camera2ClientBase: Closed Camera 0. Client was: com.app.name (PID 19796, UID 10469)
12-01 11:47:34.547  1938  2329 I PGServer: checkPkgType. calling pkg: com.huawei.android.hwaps
```

### Camera Device

```json
// on HUAWEI P20 Lite (Android 9):
// Back camera:
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "limited",
  "maxZoom": 4,
  "minZoom": 1,
  "maxExposure": 8,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minExposure": -8,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}

// Front camera:
{
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 3,
  "minZoom": 1,
  "maxExposure": 8,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minExposure": -8,
  "name": "FRONT (1)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "front",
  "id": "1"
}
```

### Device

HUAWEI P20 Lite (Android 9), Xiaomi Redmi 9C (Android 10)

### VisionCamera Version

3.6.12

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by paulobunga** [comment]
Just experienced the same, issue. While trying to Switch between back camera and front camera after navigating to new page

**Comment by cherish404** [comment]
I have the same issue in v3.6.13

**Comment by lewy12121212** [comment]
same in version 3.6.16 :/ 
My simple solution is set camera position to default on component unmount. If you navigate to different page witch camera set different than default -> error occur, But if you change active camera to default before navigate, error is not occur.

  const [activeCamera, setActiveCamera] = useState<'front' | 'back'>('back');

  useFocusEffect(
    useCallback(() => {
      return () => {
        setActiveCamera('back');
      };
    }, []),
  );

Is work for me :).

**Comment by mrousavy** [comment]
Hey! Thanks for reporting this issue.

I've been working the past days on making sure the Camera lifecycle is safely handled and released when needed to make sure this crash doesn't occur anymore.

I just created a PR for this - can you please this to see if that fixes the issue for you? https://github.com/mrousavy/react-native-vision-camera/pull/2339

If this fixes your issue, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support me / thank me for building VisionCamera and continuously improving it. 

If this does not fix your issue, please clone the repo, check out the branch `fix/blackscreen` (the PR above), run the Example app, reproduce your issue there and share the `adb logcat` logs with me (upload to pastebin or gist) so I can investigate this further.

Thank you! 🙏
