### ISSUE TITLE
🐛 [Android] Crash when recording v3.6.14

### ISSUE THREAD

**Issue by Fgabz** [cuvent/react-native-vision-camera#2269]
### What's happening?

When I'm trying to record on my Oneplus 8T, it's failing right away. It's making sense when checking the Kotlin code 

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
    val profiles = CamcorderProfile.getAll(cameraId, quality)
    if (profiles != null) {
      val best = profiles.videoProfiles.filterNotNull().minBy {
        abs(it.width * it.height - targetResolution.width * targetResolution.height)
      }

      if (best != null) {
        recommendedProfile = RecommendedProfile(
          best.bitrate,
          best.codec,
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) best.bitDepth else 8,
          best.frameRate
        )
      }
    }
  }
  ```
  
 if `profiles.videoProfiles.filterNotNull()` return an empty list calling right after `minBy` will throw java.util.NoSuchElementException. Not related to the bug but `minBy` is deprecated in Kotlin since 1.4
  
  

### Reproduceable Code

```tsx
<Camera
          isActive={!isPreviewEnabled}
          ref={setCameraRef}
          device={device}
          {...recordVideoOptions}
          video={true}
          torch={recordVideoOptions.flash}
          audio={true}
          videoStabilizationMode={stabilizationMode}
          format={cameraFormat}
          style={{ flex: 1 }}
        />


const cameraRecordingOptions: RecordVideoOptions = {
    //maxDuration: MAX_RECORDING_DURATION_IN_SECONDS,
    flash: "off",
    videoCodec: "h265",
    videoBitRate: 5_000_000,
    onRecordingFinished: (video) => setRecordPreviewUri(video.path),
    onRecordingError: (error) => console.error(error),
  }

 const [stabilizationMode, setStabilizationMode] = useState<
    "off" | "cinematic-extended" | "cinematic"
  >("cinematic-extended")
```

### Relevant log output

```shell
{"cause": {"message": null, "stacktrace": "java.util.NoSuchElementException
	at com.mrousavy.camera.extensions.RecordingSession_getRecommendedBitRateKt.getRecommendedBitRate(RecordingSession+getRecommendedBitRate.kt:107)
	at com.mrousavy.camera.core.RecordingSession.getBitRate(RecordingSession.kt:132)
	at com.mrousavy.camera.core.RecordingSession.<init>(RecordingSession.kt:37)
	at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:532)
	at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:34)
	at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying to start a video recording! null", "userInfo": null}
```
```


### Camera Device

```json
"yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 3264,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1472
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 3200,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 2400
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 3168,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1440
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 3000,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 3000
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2880,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 2160
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2592,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1944
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2448,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 2448
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2688,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1512
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2592,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1168
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2376,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2304,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1728
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 2160,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1944,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1944
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 864
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 822
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1600,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1200
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1600,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 800
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1600,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1584,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1440,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 960
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 768
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1024,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 768
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1200,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1200
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1188,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 540
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1200,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 540
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 1080,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 840,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 360
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 400
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 792,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 360
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 720,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 540
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 720,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 640
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 360
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 352,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 288
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off",
        "cinematic-extended"
      ],
      "maxZoom": 10,
      "supportsDepthCapture": false,
      "maxISO": 5699,
      "minISO": 100,
      "minFps": 1,
      "videoWidth": 176,
      "supportsVideoHdr": false,
      "videoHeight": 144,
      "supportsPhotoHdr": false,
      "photoWidth": 176,
      "fieldOfView": 80.26128467726949,
      "maxFps": 30,
      "photoHeight": 144
    }
  ],
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 1,
  "maxExposure": 72,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minExposure": -72,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Oneplus 8T

### VisionCamera Version

3.6.14

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Just fixed this in https://github.com/mrousavy/react-native-vision-camera/pull/2389!
