### ISSUE TITLE
🐛 Android: Intermittent crash going from codeScanner to photo Camera

### ISSUE THREAD

**Issue by spsaucier** [cuvent/react-native-vision-camera#2294]
### What's happening?

`navigation.navigate(...)` directly from Camera Scan screen to Camera Photo screen seems to cause a race which sometimes works properly but sometimes causes either an ANR or a crash.

ANR after dismissing this:
![Screenshot_20231213_105803_Veho](https://github.com/mrousavy/react-native-vision-camera/assets/596143/a5c52263-42b7-4826-b0c5-b16db109baf1)

I tried building the Example app and was unable to get the JS build working:
```
Error: While trying to resolve module `@mgcrea/vision-camera-code-scanner` from file `vision-camera-barcode-scanner/example/src/App.tsx`, the package `vision-camera-barcode-scanner/example/node_modules/@mgcrea/vision-camera-code-scanner/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`vision-camera-barcode-scanner/example/node_modules/@mgcrea/vision-camera-code-scanner/dist/index.js`.
```

### Reproduceable Code

```tsx
// navigation.navigate(...) from Scan to Photo camera screens


const device = useCameraDevice('back', {
  physicalDevices: [
    'ultra-wide-angle-camera',
    'wide-angle-camera',
    'telephoto-camera',
  ],
});

// Scanner
{device != null && hasPermission && (
  <Camera
    key={`${resetKey}`}
    onError={error => {
      if (error.message.includes('CameraDevice was already closed')) {
        setResetKey(prev => prev + 1);
      }
    }}
    style={styles.preview}
    device={device}
    isActive={isFocused}
    codeScanner={onCodeScanned}
    orientation="portrait"
    format={format}
    resizeMode="contain"
    enableZoomGesture
    enableHighQualityPhotos={false}
    torch={useTorch ? 'on' : 'off'}
  ></Camera>
)}


// Photo
{preview && device != null && hasPermission ? (
  <Camera
    key={`${resetKey}`}
    onError={error => {
      if (
        error.message.includes('CameraDevice was already closed')
      ) {
        setResetKey(prev => prev + 1);
      }
    }}
    // @ts-ignore - ref appears to be forwarded properly to Camera component
    ref={cameraRef}
    device={device}
    isActive={isFocused}
    style={styles.preview}
    photo
    orientation="portrait"
    torch={useTorch ? 'on' : 'off'}
    onInitialized={() => setIsInitialized(true)}
    enableZoomGesture
    enableShutterSound={false}
  />
) : (
  <View style={styles.preview} />
)}


<CaptureButton
  disabled={!isInitialized || capturing}
  confirm={confirm}
  handlePress={confirm ? handleCapture : takePicture}
/>
```

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: com.mydeveloper.MyApp, PID: 25215
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:517: Camera 0: Error clearing streaming request: Function not implemented (-38)
	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1181)
	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1343)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl.stopRepeating(CameraCaptureSessionImpl.java:425)
	at com.mrousavy.camera.core.CameraSession.destroy(CameraSession.kt:159)
	at com.mrousavy.camera.core.CameraSession.access$destroy(CameraSession.kt:57)
	at com.mrousavy.camera.core.CameraSession$close$1.invokeSuspend(CameraSession.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.mrousavy.camera.core.CameraSession.close(CameraSession.kt:99)
	at com.mrousavy.camera.CameraView.destroy(CameraView.kt:136)
	at com.mrousavy.camera.CameraViewManager.onDropViewInstance(CameraViewManager.kt:35)
	at com.mrousavy.camera.CameraViewManager.onDropViewInstance(CameraViewManager.kt:15)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:635)
	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:368)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:499)
	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:279)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:980)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8098)
	... 3 more
Caused by: android.os.ServiceSpecificException: cancelRequest:517: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2440)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:749)
	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
	... 41 more



LOGS

2023-12-15T18:18:51.324Z
1334
aaa_hal_sttCtrl
[resume] 
2023-12-15T18:18:51.329Z
25215
CameraSession
Camera Device android.hardware.camera2.impl.CameraDeviceImpl@70c408b has been disconnected!
com.mrousavy.camera.core.CameraDisconnectedError: [session/camera-has-been-disconnected] The given Camera device (id: 0) has been disconnected! Error: CAMERA_IS_DISABLED_BY_ANDROID
	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onError(CameraManager+openCamera.kt:49)
	
2023-12-15T18:18:51.329Z
25215
CameraView
invokeOnError(...):
2023-12-15T18:18:51.330Z
25215
System.err
com.mrousavy.camera.core.CameraDisconnectedError: [session/camera-has-been-disconnected] The given Camera device (id: 0) has been disconnected! Error: CAMERA_IS_DISABLED_BY_ANDROID
2023-12-15T18:18:51.330Z
25215
System.err
	at com.mrousavy.camera.extensions.CameraManager_openCameraKt$openCamera$2$callback$1.onError(CameraManager+openCamera.kt:49)
2023-12-15T18:18:51.331Z
25215
System.err
	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1851)
2023-12-15T18:18:51.331Z
25215
System.err
	at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
2023-12-15T18:18:51.331Z
25215
System.err
	at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
2023-12-15T18:18:51.331Z
25215
System.err
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
2023-12-15T18:18:51.331Z
25215
System.err
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
2023-12-15T18:18:51.331Z
25215
System.err
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
2023-12-15T18:18:51.332Z
25215
System.err
	at android.os.Handler.handleCallback(Handler.java:980)
2023-12-15T18:18:51.332Z
25215
System.err
	at android.os.Handler.dispatchMessage(Handler.java:104)
2023-12-15T18:18:51.332Z
25215
System.err
	at android.os.Looper.loopOnce(Looper.java:238)
2023-12-15T18:18:51.332Z
25215
System.err
	at android.os.Looper.loop(Looper.java:357)
2023-12-15T18:18:51.332Z
25215
System.err
	at android.os.HandlerThread.run(HandlerThread.java:85)
2023-12-15T18:18:51.352Z
1334
sttiopipe
[dequeOutBuf] WARNING: waitBufRdy:VF_EN=0, dma(0x3)
2023-12-15T18:18:51.352Z
1334
sttiopipe
[dequeOutBuf] WARNING: waitBufRdy:VF_EN=0, dma(0x4)
2023-12-15T18:18:51.352Z
1334
StatisticPipe
[deque] WARNING: TG1 deque port_13:already stopped
2023-12-15T18:18:51.352Z
1334
StatisticPipe
[deque] WARNING: TG1 deque port_12:already stopped
2023-12-15T18:18:51.352Z
1334
aao_buf_mgr
[dequeueHwBuf] abort after sttPipe deque
2023-12-15T18:18:51.352Z
1334
TaskAFNormal
[destroy] +
2023-12-15T18:18:51.352Z
1334
TaskAFNormal
[destroy] -
2023-12-15T18:18:51.353Z
1334
aaa_hal_sttCtrl
[abortDeque] 
2023-12-15T18:18:51.353Z
1334
afo_buf_mgr
[abortDequeue] abortDma done
2023-12-15T18:18:51.353Z
1334
afo_buf_mgr
[abortDequeue] +
2023-12-15T18:18:51.353Z
1334
afo_buf_mgr
[abortDequeue] -
2023-12-15T18:18:51.353Z
1334
HwIRQ3A
[flush] VSIrq flush + 0
2023-12-15T18:18:51.353Z
1334
HwIRQ3A
[flush] VSIrq flush + 1
2023-12-15T18:18:51.353Z
1334
TaskMgr
[sendEvent] TaskEvent:PreivewEnd
2023-12-15T18:18:51.353Z
1334
Task3APv
[destroy] +
2023-12-15T18:18:51.353Z
1334
Task3APv
[destroy] -
2023-12-15T18:18:51.353Z
1334
TaskMgr
[sendEvent] Remove Task(0)
2023-12-15T18:18:51.353Z
1334
aaa_hal_sttCtrl
[stopStt]
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "maxExposure": 12,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minExposure": -12,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Moto G Stylus (2022), Google Pixel 6

### VisionCamera Version

3.6.12

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! Thanks for reporting this issue.

I've been working the past days on making sure the Camera lifecycle is safely handled and released when needed, so this crash doesn't occur anymore.

I just created a PR for this - can you please this to see if that fixes the issue for you? https://github.com/mrousavy/react-native-vision-camera/pull/2339

If this fixes your issue, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support me / thank me for building VisionCamera and continuously improving it. 

If this does not fix your issue, please clone the repo, check out the branch `fix/blackscreen` (the PR above), run the Example app, reproduce your issue there and share the `adb logcat` logs with me (upload to pastebin or gist) so I can investigate this further.

Thank you! 🙏

**Comment by mrousavy** [comment]
Hey, did you try the latest version?
