### ISSUE TITLE
🐛 There is a NullPointerException here because CameraCharacteristics cannot get the SENSOR_INFO_PHYSICAL_SIZE value of the camera device

### ISSUE THREAD

**Issue by BrainLei** [cuvent/react-native-vision-camera#2602]
### What's happening?

There is a NullPointerException here because CameraCharacteristics cannot get the SENSOR_INFO_PHYSICAL_SIZE value of the camera device.
This camera device is connected to Android via USB.

Output error:
`
java.lang.NullPointerException
at com.mrousavy.camera.core.CameraDeviceDetails.<init>(CameraDeviceDetails.kt:43)
at com.mrousavy.camera.CameraDevicesManager.getDevicesJson(CameraDevicesManager.kt:67)
at com.mrousavy.camera.CameraDevicesManager.getConstants(CameraDevicesManager.kt:84)
at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:127)
`
Or
`
java.lang.NullPointerException
at com.mrousavy.camera.core.CameraDeviceDetails.<init>(CameraDeviceDetails.kt:43)
at com.mrousavy.camera.CameraDevicesManager.getDevicesJson(CameraDevicesManager.kt:63)
at com.mrousavy.camera.CameraDevicesManager.sendAvailableDevicesChangedEvent(CameraDevicesManager.kt:71)
at com.mrousavy.camera.CameraDevicesManager$callback$1.onCameraAvailable(CameraDevicesManager.kt:36)
at android.hardware.camera2.CameraManager$CameraManagerGlobal$3.run(CameraManager.java:1151)
`

I confirmed through Debug that the cause of the problem is:
When the value of SENSOR_INFO_PHYSICAL_SIZE is obtained through the CameraCharacteristics object in the constructor of CameraDeviceDetails, null is returned.
Source code:
`
val sensorSize = characteristics.get(CameraCharacteristics.SENSOR_INFO_PHYSICAL_SIZE)!!
`

### Reproduceable Code

```tsx
<Camera
ref={cameraRef}
device={frontCamera}
isActive={props.camera.isActive.value}
photo={true}
style={props.style}
/>
```

### Relevant log output

```shell
java.lang.NullPointerException
at com.mrousavy.camera.core.CameraDeviceDetails.<init>(CameraDeviceDetails.kt:43)
at com.mrousavy.camera.CameraDevicesManager.getDevicesJson(CameraDevicesManager.kt:67)
at com.mrousavy.camera.CameraDevicesManager.getConstants(CameraDevicesManager.kt:84)
at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:127)

//
java.lang.NullPointerException
at com.mrousavy.camera.core.CameraDeviceDetails.<init>(CameraDeviceDetails.kt:43)
at com.mrousavy.camera.CameraDevicesManager.getDevicesJson(CameraDevicesManager.kt:63)
at com.mrousavy.camera.CameraDevicesManager.sendAvailableDevicesChangedEvent(CameraDevicesManager.kt:71)
at com.mrousavy.camera.CameraDevicesManager$callback$1.onCameraAvailable(CameraDevicesManager.kt:36)
at android.hardware.camera2.CameraManager$CameraManagerGlobal$3.run(CameraManager.java:1151)
```

### Camera Device

```json
{
  "formats": [
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 320,
      "supportsVideoHdr": false,
      "videoHeight": 240,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 320,
      "supportsVideoHdr": false,
      "videoHeight": 240,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 320,
      "supportsVideoHdr": false,
      "videoHeight": 240,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 600
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 320,
      "supportsVideoHdr": false,
      "videoHeight": 240,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 320,
      "supportsVideoHdr": false,
      "videoHeight": 240,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1024
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 320,
      "supportsVideoHdr": false,
      "videoHeight": 240,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 640,
      "supportsVideoHdr": false,
      "videoHeight": 480,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 640,
      "supportsVideoHdr": false,
      "videoHeight": 480,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 640,
      "supportsVideoHdr": false,
      "videoHeight": 480,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 600
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 640,
      "supportsVideoHdr": false,
      "videoHeight": 480,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 640,
      "supportsVideoHdr": false,
      "videoHeight": 480,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1024
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 640,
      "supportsVideoHdr": false,
      "videoHeight": 480,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 800,
      "supportsVideoHdr": false,
      "videoHeight": 600,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 800,
      "supportsVideoHdr": false,
      "videoHeight": 600,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 800,
      "supportsVideoHdr": false,
      "videoHeight": 600,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 600
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 800,
      "supportsVideoHdr": false,
      "videoHeight": 600,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 800,
      "supportsVideoHdr": false,
      "videoHeight": 600,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1024
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 800,
      "supportsVideoHdr": false,
      "videoHeight": 600,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 720,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 720,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 720,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 600
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 720,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 720,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1024
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 720,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 1024,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 1024,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 1024,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 600
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 1024,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 1024,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1024
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1280,
      "supportsVideoHdr": false,
      "videoHeight": 1024,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1080
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1920,
      "supportsVideoHdr": false,
      "videoHeight": 1080,
      "supportsPhotoHdr": false,
      "photoWidth": 320,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 240
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1920,
      "supportsVideoHdr": false,
      "videoHeight": 1080,
      "supportsPhotoHdr": false,
      "photoWidth": 640,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 480
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1920,
      "supportsVideoHdr": false,
      "videoHeight": 1080,
      "supportsPhotoHdr": false,
      "photoWidth": 800,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 600
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1920,
      "supportsVideoHdr": false,
      "videoHeight": 1080,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 720
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1920,
      "supportsVideoHdr": false,
      "videoHeight": 1080,
      "supportsPhotoHdr": false,
      "photoWidth": 1280,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1024
    },
    {
      "autoFocusSystem": "contrast-detection",
      "pixelFormats": [
        "yuv",
        "native"
      ],
      "videoStabilizationModes": [
        "off",
        "off"
      ],
      "maxZoom": 1,
      "supportsDepthCapture": false,
      "maxISO": 0,
      "minISO": 0,
      "minFps": 1,
      "videoWidth": 1920,
      "supportsVideoHdr": false,
      "videoHeight": 1080,
      "supportsPhotoHdr": false,
      "photoWidth": 1920,
      "fieldOfView": 0,
      "maxFps": 30,
      "photoHeight": 1080
    }
  ],
  "sensorOrientation": "portrait",
  "hardwareLevel": "limited",
  "maxZoom": 1,
  "minZoom": 1,
  "maxExposure": 0,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "telephoto-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minExposure": 0,
  "name": "EXTERNAL (/dev/video5)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "external",
  "id": "/dev/video5"
}
```

### Device

15in-l-Series-4-USBC-v(Android 10)

### VisionCamera Version

3.7.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Fixed in latest commit.
