### ISSUE TITLE
🐛 Adding frameprocessor to camera causes error

### ISSUE THREAD

**Issue by RickdeBruijn** [cuvent/react-native-vision-camera#2619]
### What's happening?

I'm trying to follow the guide [react-native-vision-camera guide](https://react-native-vision-camera.com/docs/guides/)

It works untill i get to the frameprocessor example, when adding frameProcessor={frameProcessor} to the camera it returns an error.

### Reproduceable Code

```tsx
import React from 'react';
import {
  Camera,
  useCameraDevice,
  useCameraPermission,
  useFrameProcessor,
} from 'react-native-vision-camera';
import NoCameraDeviceError from './error/NoCameraDeviceError.tsx';

const CameraComp = () => {
  const {hasPermission, requestPermission} = useCameraPermission();
  const device = useCameraDevice('back');

  const onError = (e: any) => {
    console.log(e);
  };

  const frameProcessor = useFrameProcessor(frame => {
    'worklet';
    console.log(frame.pixelFormat);
  }, []);

  if (hasPermission) {
    if (device == null) {
      return <NoCameraDeviceError />;
    }
    return (
      <Camera
        frameProcessor={frameProcessor}
        device={device}
        isActive={true}
        onError={onError}
      />
    );
  } else {
    return requestPermission();
  }
};

export default CameraComp;
```

### Relevant log output

```shell
2024-02-29 17:22:30.163  8459-8514  VideoPipeline           com.edgecam                          E  FrameProcessor/ImageReader pipeline threw an error!
                                                                                                    com.facebook.jni.CppException: Compiling JS failed: 1:1:invalid empty parentheses '( )' Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p
                                                                                                    	at com.mrousavy.camera.frameprocessor.FrameProcessor.call(Native Method)
                                                                                                    	at com.mrousavy.camera.CameraView.onFrame(CameraView.kt:248)
                                                                                                    	at com.mrousavy.camera.core.VideoPipeline._init_$lambda$0(VideoPipeline.kt:111)
                                                                                                    	at com.mrousavy.camera.core.VideoPipeline.$r8$lambda$EMriwS_FKhtjTFtppM84Z5V8tiI(Unknown Source:0)
                                                                                                    	at com.mrousavy.camera.core.VideoPipeline$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
                                                                                                    	at android.media.ImageReader$1.run(ImageReader.java:947)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-02-29 17:22:30.163  8459-8514  CameraView              com.edgecam                          E  invokeOnError(...):
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  com.facebook.jni.CppException: Compiling JS failed: 1:1:invalid empty parentheses '( )' Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  	at com.mrousavy.camera.frameprocessor.FrameProcessor.call(Native Method)
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  	at com.mrousavy.camera.CameraView.onFrame(CameraView.kt:248)
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  	at com.mrousavy.camera.core.VideoPipeline._init_$lambda$0(VideoPipeline.kt:111)
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  	at com.mrousavy.camera.core.VideoPipeline.$r8$lambda$EMriwS_FKhtjTFtppM84Z5V8tiI(Unknown Source:0)
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  	at com.mrousavy.camera.core.VideoPipeline$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
2024-02-29 17:22:30.164  8459-8514  System.err              com.edgecam                          W  	at android.media.ImageReader$1.run(ImageReader.java:947)
2024-02-29 17:22:30.165  8459-8514  System.err              com.edgecam                          W  	at android.os.Handler.handleCallback(Handler.java:958)
2024-02-29 17:22:30.165  8459-8514  System.err              com.edgecam                          W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2024-02-29 17:22:30.165  8459-8514  System.err              com.edgecam                          W  	at android.os.Looper.loopOnce(Looper.java:205)
2024-02-29 17:22:30.167  8459-8514  System.err              com.edgecam                          W  	at android.os.Looper.loop(Looper.java:294)
2024-02-29 17:22:30.169  8459-8514  System.err              com.edgecam                          W  	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-02-29 17:22:30.182  8459-9941  ReactNativeJS           com.edgecam                          I  { [unknown/unknown: [unknown/unknown] Compiling JS failed: 1:1:invalid empty parentheses '( )' Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p]
                                                                                                      name: 'unknown/unknown',
                                                                                                      _code: 'unknown/unknown',
                                                                                                      _message: '[unknown/unknown] Compiling JS failed: 1:1:invalid empty parentheses \'( )\' Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p',
                                                                                                      _cause: 
                                                                                                       { stacktrace: 'com.facebook.jni.CppException: Compiling JS failed: 1:1:invalid empty parentheses \'( )\' Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p\n\tat com.mrousavy.camera.frameprocessor.FrameProcessor.call(Native Method)\n\tat com.mrousavy.camera.CameraView.onFrame(CameraView.kt:248)\n\tat com.mrousavy.camera.core.VideoPipeline._init_$lambda$0(VideoPipeline.kt:111)\n\tat com.mrousavy.camera.core.VideoPipeline.$r8$lambda$EMriwS_FKhtjTFtppM84Z5V8tiI(Unknown Source:0)\n\tat com.mrousavy.camera.core.VideoPipeline$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)\n\tat android.media.ImageReader$1.run(ImageReader.java:947)\n\tat android.os.Handler.handleCallback(Handler.java:958)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:205)\n\tat android.os.Looper.loop(Looper.java:294)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\n',
                                                                                                         message: 'Compiling JS failed: 1:1:invalid empty parentheses \'( )\' Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p' } }
2024-02-29 17:22:30.187  8459-8514  VideoPipeline           com.edgecam                          I  ImageReader::onImageAvailable!
2024-02-29 17:22:30.196  8459-8514  HermesVM                com.edgecam                          I  Compiling JS failed: 1:1:invalid empty parentheses '( )',  Buffer size 3 starts with: 280a29 and has protection mode(s): rw-p
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 1,
  "maxExposure": 9,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minFocusDistance": 5,
  "minExposure": -9,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

pixel_3a android 14.0 (U) - API 34

### VisionCamera Version

3.9.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by ababol** [comment]
Hi @CHAOSdonut, 👋  face the same issue

Use `"react-native-worklets-core": "0.2.0"` not `0.3.0` :)

**Comment by RickdeBruijn** [comment]
Hi,
I tried downgrading to "0.2.0", got the error that it was missing "string-hash-64",
installed that but running it gives the same error as before.

**Comment by mrousavy** [comment]
Did you add the plugin to babel and restart metro with clean cache?.

**Comment by poju3185** [comment]
I face the same issue, and even the missing "string-hash-64" part after downgrading. It was solved by simply npm install the package.

**Comment by neilanthonyte** [comment]
actually non of the plugin works . . I tried every plugin and they all broke the react native vision camera . . I posted the error to one of the plugin
https://github.com/mgcrea/vision-camera-barcode-scanner/issues/26

the plugin totally broke this library and I had to re-create the react native project to have this library run again

**Comment by RickdeBruijn** [comment]
@mrousavy,

This worked, i had tried clearing IDE and emulator cache before. But had not yet cleared the right cache.

```npm start -- --reset-cache``` Did the trick for me.
