### ISSUE TITLE
🐛 [Android] App crash, Open camera view -> Deny permission from app-info premissions -> Come back to app

### ISSUE THREAD

**Issue by Nachcha** [cuvent/react-native-vision-camera#2676]
### What's happening?

I need to scan a QR code, The Process is going well but 
The following steps crash the mobile app
1: Open the camera view
2: Go to app info permissions
3: Disable camera permission from the app info
4: Open the minimized app

### Reproduceable Code

```tsx
import React, {useEffect} from 'react';
import {Dimensions, Image, Linking, View} from 'react-native';
import {
  Camera,
  CameraDevice,
  useCameraDevice,
  useCameraPermission,
  useCodeScanner,
} from 'react-native-vision-camera';
import ActionButton from '@components/ActionButton/ActionButton';
import styles from './style';
import {getScaleNumber} from '@utils/refDimention';
import {Text} from 'react-native';
// parameter types
type ParamTypes = {
  setVisibleQR: any;
  onSuccess: Function;
};

const QrCodeScanner = ({setVisibleQR, onSuccess}: ParamTypes) => {
  const cancelQR = () => {
    setVisibleQR(false);
  };
  const {hasPermission, requestPermission} = useCameraPermission();
  const [stretchFix, setStretchFix] = React.useState(0);
  const [isActive, setIsActive] = React.useState<boolean>(true);
  const device = useCameraDevice('back');
  const codeScanner = useCodeScanner({
    codeTypes: ['qr', 'ean-13'],
    onCodeScanned: codes => {
      // console.log(`Scanned data ${JSON.stringify(codes)} codes!`);
      setIsActive(false);
      console.log(`Scanned ${JSON.stringify(codes[0].value)} codes!`);
      onSuccess(JSON.stringify(codes[0].value));
    },
  });
  useEffect(() => {
    setIsActive(true);
    if (!hasPermission) {
      console.log('hasPermission', hasPermission);
      requestPermission();
    }
  }, []);

  return (
    <View style={styles.container}>
      {hasPermission && device ? (
        <View style={styles.cameraContainer}>
          <Camera
            device={device as CameraDevice}
            codeScanner={codeScanner}
            resizeMode="contain"
            isActive={isActive}
            style={{
              height: '140%',
              marginVertical: getScaleNumber(20),
              width: Dimensions.get('screen').width - 1 + stretchFix,
            }}
            onInitialized={() => setStretchFix(1)}
          />
        </View>
      ) : (
        <View style={styles.messageContainer}>
          <Text style={styles.messageText}>
            Looks like you have not allowed camera permission
          </Text>
          <Image
            source={require('../../assets/images/camera-denied.png')}
            resizeMode="contain"
            style={styles.cameraImage}
          />
          <Text style={styles.messageText}>
            Navigate to{' '}
            <Text
              onPress={() => {
                Linking.openSettings();
              }}
              style={styles.messagePressableText}>
              Settings
            </Text>{' '}
            in your mobile and grant camera permission for Apollo Art
          </Text>
        </View>
      )}
      <View style={styles.bottomBtn}>
        <ActionButton type="fill" title="Cancel" onPress={() => cancelQR()} />
      </View>
    </View>
  );
};
export default QrCodeScanner;
```

### Relevant log output

```shell
E  FATAL EXCEPTION: main
                                                                                                    Process: com.cidigitaldisplays.apollo, PID: 20956
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cidigitaldisplays.apollo/com.cidigitaldisplays.apollo.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:225)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7563)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
                                                                                                    Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84)
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:377)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
                                                                                                    	at com.cidigitaldisplays.apollo.MainActivity.onCreate(MainActivity.kt:17)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:225) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7563) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994) 
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:377) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                                                                                                    	at com.cidigitaldisplays.apollo.MainActivity.onCreate(MainActivity.kt:17) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:225) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7563) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994) 
                                                                                                    Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
                                                                                                    	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:57)
                                                                                                    	at com.swmansion.rnscreens.ScreenStackFragment.<init>(ScreenStackFragment.kt:38)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613) 
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:377) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                                                                                                    	at com.cidigitaldisplays.apollo.MainActivity.onCreate(MainActivity.kt:17) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:225) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7563) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994) 
```

### Camera Device

```json
const device = useCameraDevice('back')
```

### Device

Android

### VisionCamera Version

^3.9.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey - I think this issue has been fixed in [VisionCamera 4.0.0](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0). 🥳 

Please try V4 and let me know if you still experience this issue;
- if not, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support the development of VisionCamera and thank me for my time spent on fixing bugs and building new features.
- if you still see this issue, please comment and we can re-open this. But please update your native logs with the native (Xcode/Android Studio) logs from running VisionCamera V4 so I can investigate this.
