### ISSUE TITLE
🐛 InitializationException - Device reporting less cameras than anticipated

### ISSUE THREAD

**Issue by ncoen97** [cuvent/react-native-vision-camera#3179]
### What's happening?

I am encountering a crash reported in Crashlytics, related to `androidx.camera.core.InitializationException`. The issue seems to occur when the app attempts to initialize the camera, and it reports fewer cameras than expected, resulting in a `CameraUnavailableException`. This crash happens on real devices, and it mentions retrying initialization. However, I cannot reproduce the issue locally on my test devices, so I’m unable to investigate further in a controlled environment.

### Reproduceable Code

```tsx
const QRCodeScanner: React.FC<QRCodeScannerProps> = ({
  onCodeScanned,
  loading,
  handlePermissionBlocked,
}) => {
  const device = useCameraDevice('back');
  const camera = useRef<Camera>(null);
  const isFocused = useIsFocused();
  const appState = useAppState();
  const [cameraReady, setCameraReady] = useState(false);
  const {onLayout, layout} = useLayout();
  const hasPermission = useCameraPermissions(handlePermissionBlocked);
  const codeScanner = useCodeScanner({
    codeTypes: ['qr'],
    onCodeScanned,
  });

  const isActive = isFocused && appState === 'active' && !!layout && !loading;
  const isScanning = isActive && cameraReady;

  const onError = (err: CameraRuntimeError | string) =>
    Analytics.logError(err, 'Camera error');

  return device && hasPermission ? (
    <View style={styles.container} onLayout={onLayout}>
      {isScanning ? (
        <QRMask
          containerHeight={layout.height}
          containerWidth={layout.width}
        />
      ) : null}
      {!isScanning ? (
        <View style={styles.loaderContainer}>
          <DefaultLoader />
        </View>
      ) : null}
      <Camera
        ref={camera}
        onError={onError}
        photo={false}
        device={device}
        codeScanner={codeScanner}
        isActive={isActive}
        style={StyleSheet.absoluteFill}
        onPreviewStarted={() => setCameraReady(true)}
        onStopped={() => setCameraReady(false)}
      />
    </View>
  ) : null;
};
```

### Relevant log output

```shell
Crashlytics report:

Fatal Exception: androidx.camera.core.InitializationException
androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0

androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX (CameraX.java:433)
```

### Camera Device

```
I cannot provide the JSON for the camera device since the issue occurs in production and I cannot reproduce it locally.
```

### Device

The crash affects multiple devices, with the following breakdown:  Motorola (69%) Samsung (17%) Xiaomi (14%). Operating system versions:  Android 11 (62%) Android 13 (21%) Android 12 (17%).

### VisionCamera Version

4.5.2

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by LukasMod** [comment]
Hey, I have same problem on production, multiple crashes in crashlytics (its small % of users, but enough to be one of main reason for our crashes currently). Maybe my information will help you somehow to debug this.
    
```
"react-native": "0.73.8",
"react-native-vision-camera": "4.5.0"
```
I add stacktarce from one of crashes. 
[stacktrace.txt](https://github.com/user-attachments/files/16963668/stacktrace.txt)

Name of error is `androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX (CameraX.java:369)`. Mostly (46%) its Xiaomi devices, different androids.

**Comment by nthegedus** [comment]
Hi, same problem here in production too.

```
"react-native": "0.74.1",
"react-native-vision-camera": "4.3.2",
```

In Crashlytics there's this error description:
![Captura de Tela 2024-09-11 às 11 22 37](https://github.com/user-attachments/assets/a33255ef-dcea-4fad-8fa3-428c5be5f907)

**Comment by mrousavy** [comment]
Well, Camera APIs on Android suck.

**Comment by efstathiosntonas** [comment]
Started seing this out of the sudden on Android 9 on 4.5.2, rn 0.75.3. 

Can reproduce it locally on Pixel 4XL emulator running Android 9. @mrousavy do you need any logs or screw camera apis 😂?

**Comment by efstathiosntonas** [comment]
Some extra information around the bug, Simulator Pixel 4XL Android 9, same thing happens on real devices though.

1. Open device camera app
2. open your app
3. try to pick a photo, throws: ` [session/recoverable-error: An unknown error occurred while creating the Camera Session, but the Camera can recover from it.]
 ERROR  [device/camera-already-in-use: The given Camera Device is already in use!]`
4. Close your app
5. try to open device camera app again: Android throws: `Camera error Can't connect to camera` so it seems it brakes Android system too.
6. only way to recover device camera app is to cold boot the emulator

stack:

```logcat
FATAL EXCEPTION: pool-26-thread-2 (Ask Gemini)
Process: com.xxxxx, PID: 10365
androidx.camera.core.InitializationException: androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0
 at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:433)
 at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@81d901b, java.util.concurrent.ThreadPoolExecutor@660c5b8[Running, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 2]]
Caused by: androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0
```

edit: tried with `4.5.3` (with CameraX@1.5.0-alpha01) and it throws the same error.

**Comment by LuongTruong** [comment]
Hello guys, I just found a way to reproduce the issue.

1. From Edit Android Emulator -> Show Advanced Settings -> Camera: Front -> None and Back -> None
2. Run your app on that emulator and the issue will appear

Thanks guys for pointing nearly all the versions that have the issue. As a result I use `react-native-vision-camera: 4.2.1`.

Below is my final version in `package.json`

```
"dependencies": {
  "react": "18.2.0",
  "react-native": "0.73.9",
  "react-native-reanimated": "3.15.2",
  "react-native-vision-camera": "4.2.1",
},
```

Hope it can help.

**Comment by Rag0n** [comment]
Same issue with react-native-vision-camera 4.5.2

**Comment by Nader-CS** [comment]
same issue

**Comment by mannoeu** [comment]
Same here:

```
react-native: 0.73.4
react-native-vision-camera: ^4.5.2
```

![image](https://github.com/user-attachments/assets/32424457-76fd-412c-a400-7a1cc2dfd7da)


```
androidx.camera.core.InitializationException: androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0
        at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:433)
        at androidx.camera.core.CameraX$$ExternalSyntheticLambda0.run(Unknown:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)

Caused by: androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0
        at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:433)
        at androidx.camera.core.CameraX$$ExternalSyntheticLambda0.run(Unknown:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ShchipskiiYura** [comment]
same problem

**Comment by imamrobani** [comment]
same issue 

"react-native": "0.73.9",
"react-native-vision-camera": "^4.5.2"

**Comment by Nader-CS** [comment]
any help ?

**Comment by 39otrebla** [comment]
Same issue here.

**Comment by DarshanSavaliyaGitHub** [comment]
Same issue here...

**Comment by marcos-cunha-gringo** [comment]
We are having the same issue here:
 - react-native-vision-camera: 4.5.0;
 - react-native: 0.74.5;

**Comment by Nader-CS** [comment]
any updates ?

**Comment by mannoeu** [comment]
> any updates ?

Unfortunately, no one can reproduce the error concisely. :(

**Comment by UKMIITB** [comment]
Has the camerax version has been updated to 1.4.0 ?

I am also facing this issue post version update & have raised it here.
Please upvote if the issue is same

Have raised it here
https://issuetracker.google.com/issues/383220395

**Comment by mrousavy** [comment]
> Has the camerax version has been updated to 1.4.0 ?

https://github.com/mrousavy/react-native-vision-camera/blob/54df86ace1716039f690e865c97f29f87dfe43b7/package/android/build.gradle#L185-L192

**Comment by hongying-yang** [comment]
@mrousavy We are using version 4.6.1, and our build.gradle file is the same as the one you provided, 1.5.0-alpha03. However, some phones are still reporting this error.

**Comment by Nader-CS** [comment]
still same

**Comment by hozdemir** [comment]
still same, we get this error on some devices. do you have any suggestions for a solution?

**Comment by kadiraydinli** [comment]
Still same. Is there a solution for this?

**Comment by Nader-CS** [comment]
any updates ? thie issue happen today for 15 user.

**Comment by JuhilGajeraGitHub** [comment]
I am also getting this crash in firebase crashlytics

**Comment by levepic** [comment]
So do i

**Comment by litinskii** [comment]
+1 Same issue

**Comment by rb-adnan** [comment]
i am also getting the same error.
-- i am not able to reproduce exactly but getting this log from some devices listed below with OS version
- here's some stacktrace from dynatrace:

details:
"react-native": "0.75.4",
"react-native-vision-camera": "^4.5.3",

**Devices**
P30 Pro (46.6 %)
Galaxy A51 (26.2 %)
HUAWEI nova 5T (3.4 %)
Infinix HOT 40i (2.43 %)
Others (21.4 %)

**Operating system**
Android 10 (50 %)
Android 13 (31.1 %)
Android 11 (6.31 %)
Android 12 (4.37 %)
Others (8.25 %)

`androidx.camera.core.InitializationException: androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0

at

androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:433)

at

androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)

at

java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)

at

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)

at

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

at

java.lang.Thread.run(Thread.java:784)`

**Comment by Nader-CS** [comment]
any updates ?!

**Comment by UKMIITB** [comment]
Hi everyone,
As mentioned in the above issue tracker that this is an expected behaviour 
It was happening previously as well (with older versions), just that it was failing silently.
And now the exception is thrown.

Handling for this is to wrap the `cameraProviderFuture.get()` call with `try catch` block
Sample is shared here
https://issuetracker.google.com/issues/383220395#comment3

**Comment by mannoeu** [comment]
> Hi everyone, As mentioned in the above issue tracker that this is an expected behaviour It was happening previously as well (with older versions), just that it was failing silently. And now the exception is thrown.
> 
> Handling for this is to wrap the `cameraProviderFuture.get()` call with `try catch` block Sample is shared here https://issuetracker.google.com/issues/383220395#comment3

The app will crash? Can i ignore this error?

**Comment by mrousavy** [comment]
created a PR to potentially fix this: https://github.com/mrousavy/react-native-vision-camera/pull/3373

**Comment by Nader-CS** [comment]
anyone can confirm if this pr works ?

**Comment by rb-adnan** [comment]
@Nader-CS you need fix the variable declaration for `provider`, then should work fine.

**Comment by sorenfrederiksen** [comment]
> created a PR to potentially fix this: [#3373](https://github.com/mrousavy/react-native-vision-camera/pull/3373)

Awesome! Thanks for looking into this, @mrousavy - really appreciate your hard work 💪 

How many people in this long thread are considering supporting Marc's work? We really should be.

**Comment by sorenfrederiksen** [comment]
> created a PR to potentially fix this: [#3373](https://github.com/mrousavy/react-native-vision-camera/pull/3373)

Hey @mrousavy, 

When you've got a spare moment, can you maybe review my PR aiming to fix this issue? https://github.com/mrousavy/react-native-vision-camera/pull/3385

It follows through on what I think were your intentions, with your PR, and seems to work locally.

(And would be my first contribution to the library, so if you like making people feel special, there's that, too 💫)
