### ISSUE TITLE
🐛 Native Module 'CameraView' was null!

### ISSUE THREAD

**Issue by sergey-zakharov** [cuvent/react-native-vision-camera#495]
### What were you trying to do?

Tried building a bundle for android but caught `Native Module 'CameraView' was null!` every time

**I've check on two devices one of them (Huawei Nova 5T) turned to be with limited Camera 2 support, another (One Plus 8) - with a full support of Camera 2 (aka Level_3)**

tried with:
[*] Expo `expo r -c` on 2 devices
[*] `react-native run-android` on emulator
[*] expo build:android
[*] different versions of react-native-vision-camera
[*] different versions of NDK
[*] checked troubleshooting
[*] added maven repo (see [expo issues](https://github.com/expo/expo/issues/3639))

Everything made on Ubuntu 20
No hope to start camera on android devices for now, `pod install` while building only for android looks more upsetting

### Reproduceable Code

```tsx
import React, { useState, useEffect} from 'react';
import { Text, Platform, StatusBar, StyleSheet, View } from 'react-native';

import AppNavigator from './navigation/AppNavigator';
import {Camera, useCameraDevices} from 'react-native-vision-camera'
import { Button } from 'react-native-ui-lib';

export default function App(props) {
  const devices = useCameraDevices('wide-angle-camera')
  const device = devices.back
  const [cameraOn, setCameraOn] = useState(false)
  const [permissons, setPermissons] = useState(false)

  const getPermissons = async () => {
    const cameraPermission = await Camera.getCameraPermissionStatus()
    if (cameraPermission === 'authorized') {
      setPermissons(true)
    }
  }

  const requestPermissons = async () => {

    const newCameraPermission = await Camera.requestCameraPermission().catch((error) => console.warn("camera error:", error))
    if (newCameraPermission === 'authorized') {
      setPermissons(true)
    }
  }

  useEffect(() => {
    getPermissons()
  }, [])

  if (!permissons) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>No permissons</Text>
        <Button onPress={requestPermissons}></Button>
      </View>
    )
  }

  if (!device) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Loading</Text>
      </View>
    )
  }

  if (!cameraOn) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Turn on the camera</Text>
        <TouchableOpacity onPress={() => setCameraOn(true)} style={{ marginTop: 30, backgroundColor: '#28a745' }}>
          <Text style={{ marginHorizontal: 20, marginVertical: 10, color: 'white' }}>ON</Text>
        </TouchableOpacity>
      </View>
    )
  }

  return (
    <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={true}
    />
  )
}
```

```
settings.gradle


apply from: '../node_modules/react-native-unimodules/gradle.groovy'
includeUnimodulesProjects()

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesSettingsGradle(settings)

include ':app'

include ':react-native-vision-camera'
project(':react-native-vision-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vision-camera/android')
```
```
build.gradle

buildscript {
    ext {
        kotlinVersion = "1.4.31"
        RNNKotlinVersion = kotlinVersion
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        // ndkVersion = "23.0.7599858"
        ndkVersion = "20.1.5948944"
        VisionCamera_ndkVersion=ndkVersion
    }
    repositories {
        google()
        jcenter()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.31"
        classpath("com.android.tools.build:gradle:4.2.0")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        ...
        maven {
            // expo-camera bundles a custom com.google.android:cameraview
            // See: https://github.com/expo/expo/issues/3639
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
    }
 ```
 ```json
  app.json
{
  "name": "xxx",
  "slug": "xxx",
  "privacy": "public",
  "platforms": [
    "android"
  ],
...
}
```

### What happened instead?

Camera devices are all undefined

```Object {
  "back": undefined,
  "external": undefined,
  "front": undefined,
  "unspecified": undefined,
}```

`Camera: Native Module 'CameraView' was null! Did you run pod install?` in logs

### Relevant log output

```shell
=========== expo log ============
Camera: Native Module 'CameraView' was null! Did you run pod install?
at node_modules/react-native-vision-camera/src/Camera.tsx:47:21 in <global>
at http://192.168.10.144:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:279474:27 in <unknown>
at http://192.168.10.144:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:279358:44 in <unknown>
at http://192.168.10.144:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:171335:56 in <unknown>
at http://192.168.10.144:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:161267:60 in <unknown>
at App.js:9:0 in <global>
at index.js:4:0 in <global>
at http://192.168.10.144:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:280748:3 in global code

=============== apk log ============

10-05 12:36:15.799 28935 29007 E ReactNativeJS: Camera: Native Module 'CameraView' was null! Did you run pod install?
10-05 12:36:15.805 28935 29008 E unknown:ReactNative: console.error: Camera: Native Module 'CameraView' was null! Did you run pod install?, stack:
10-05 12:36:15.805 28935 29008 E unknown:ReactNative: construct@-1
12:41

10-05 12:35:17.580 28010 28177 W ReactNativeJS: 'camera error:', { [TypeError: null is not an object (evaluating 'b.requestCameraPermission')]
10-05 12:35:17.580 28010 28177 W ReactNativeJS: line: 1531,
10-05 12:35:17.580 28010 28177 W ReactNativeJS: column: 7119,
10-05 12:35:17.580 28010 28177 W ReactNativeJS: sourceURL: '/data/user/0/*****/files/.expo-internal/1643d28a4e9b769276d0a00431a815dd' }
```

### Device

OnePlus 8 (IN2013) Android 10, Huawei Nova 5T (YAL-L21)

### VisionCamera Version

2.8.3, 2.7.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by sergey-zakharov** [comment]
Closing in favor of #488
